import { PrismaClient, TransferType, VehicleType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🚗 Starting transfer seeding...');

  const dubai = await prisma.city.findFirst({ where: { name: 'Dubai' } });
  const uae = await prisma.country.findFirst({ where: { name: 'United Arab Emirates' } });

  if (!dubai || !uae) {
    throw new Error('Dubai or UAE not found. Please run seed-dubai.ts first.');
  }

  const transfers = [
    {
      id: 'transfer-airport-luxury-sedan',
      slug: 'dubai-airport-luxury-sedan',
      name: 'Dubai Airport Transfer - Luxury Sedan',
      description: 'Premium airport transfer service in a luxury sedan. Professional driver, meet & greet service, flight tracking included. Perfect for business travelers and those seeking comfort.',
      shortDescription: 'Luxury sedan airport transfer with meet & greet',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.LUXURY,
      fromLocation: 'Dubai International Airport (DXB)',
      toLocation: 'Dubai City Center',
      fromAddress: 'Dubai International Airport, Terminal 1, 2, 3',
      toAddress: 'Any location in Dubai City Center',
      maxPassengers: 3,
      maxLuggage: 3,
      price: 150,
      currency: 'AED',
      duration: 30,
      distance: 15,
      features: JSON.stringify([
        'Professional chauffeur',
        'Meet & greet service',
        'Flight tracking',
        'Free waiting time (60 min)',
        'Luxury Mercedes S-Class or similar',
        'Bottled water',
        'Phone chargers',
        'WiFi available',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Leather seats',
        'Spacious trunk',
        'Child seat available',
        'Wheelchair accessible',
      ]),
      included: JSON.stringify([
        'Professional driver',
        'Fuel',
        'Parking fees',
        'Toll fees',
        'Meet & greet',
        'Flight tracking',
        '60 minutes free waiting',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Extra stops',
        'Waiting time beyond 60 minutes',
      ]),
      images: JSON.stringify(['/images/transfers/luxury-sedan-1.jpg']),
      mainImage: '/images/transfers/luxury-sedan-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Mercedes-Benz',
      vehicleModel: 'S-Class',
      vehicleYear: 2024,
      vehicleColor: 'Black',
      driverLanguages: JSON.stringify(['English', 'Arabic', 'Hindi']),
      advanceBooking: 2,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      childSeat: true,
      wheelchairAccess: true,
      metaTitle: 'Dubai Airport Luxury Sedan Transfer | Premium Service',
      metaDescription: 'Book luxury sedan airport transfer in Dubai. Professional driver, meet & greet, flight tracking. Mercedes S-Class.',
      rating: 4.9,
      reviewCount: 156,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-airport-suv',
      slug: 'dubai-airport-suv-transfer',
      name: 'Dubai Airport Transfer - SUV',
      description: 'Spacious SUV airport transfer perfect for families and groups. Extra luggage space, comfortable seating for up to 6 passengers.',
      shortDescription: 'Family-friendly SUV airport transfer',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SUV,
      fromLocation: 'Dubai International Airport (DXB)',
      toLocation: 'Dubai Marina',
      maxPassengers: 6,
      maxLuggage: 6,
      price: 200,
      currency: 'AED',
      duration: 35,
      distance: 25,
      features: JSON.stringify([
        'Spacious SUV (Chevrolet Suburban or similar)',
        'Professional driver',
        'Meet & greet',
        'Flight tracking',
        'Extra luggage space',
        'Child seats available',
        'Bottled water',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Leather seats',
        'Large trunk',
        'USB charging ports',
      ]),
      included: JSON.stringify([
        'Professional driver',
        'Fuel and tolls',
        'Meet & greet',
        'Flight tracking',
        '60 minutes waiting',
      ]),
      notIncluded: JSON.stringify(['Gratuity', 'Extra stops']),
      images: JSON.stringify(['/images/transfers/suv-1.jpg']),
      mainImage: '/images/transfers/suv-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Chevrolet',
      vehicleModel: 'Suburban',
      vehicleYear: 2024,
      driverLanguages: JSON.stringify(['English', 'Arabic']),
      childSeat: true,
      rating: 4.8,
      reviewCount: 98,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-city-sedan',
      slug: 'dubai-city-transfer-sedan',
      name: 'Dubai City Transfer - Sedan',
      description: 'Comfortable sedan for city transfers. Perfect for business meetings, shopping trips, or sightseeing.',
      shortDescription: 'Affordable city transfer in comfortable sedan',
      transferType: TransferType.CITY,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Dubai Marina',
      toLocation: 'Downtown Dubai',
      maxPassengers: 4,
      maxLuggage: 2,
      price: 80,
      currency: 'AED',
      duration: 20,
      distance: 12,
      features: JSON.stringify([
        'Comfortable sedan (Toyota Camry or similar)',
        'Professional driver',
        'Air conditioning',
        'Bottled water',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Clean vehicle',
      ]),
      included: JSON.stringify(['Driver', 'Fuel', 'Parking']),
      notIncluded: JSON.stringify(['Gratuity', 'Waiting time']),
      images: JSON.stringify(['/images/transfers/sedan-1.jpg']),
      mainImage: '/images/transfers/sedan-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['English', 'Arabic', 'Urdu']),
      rating: 4.6,
      reviewCount: 234,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-vip-luxury',
      slug: 'dubai-vip-luxury-transfer',
      name: 'VIP Luxury Transfer - Premium Experience',
      description: 'Ultimate VIP transfer experience with luxury vehicle and premium service. Red carpet service, champagne, personal concierge.',
      shortDescription: 'VIP luxury transfer with premium amenities',
      transferType: TransferType.VIP,
      vehicleType: 'LUXURY',
      fromLocation: 'Dubai International Airport (DXB)',
      toLocation: 'Burj Al Arab',
      maxPassengers: 3,
      maxLuggage: 4,
      price: 500,
      currency: 'AED',
      duration: 25,
      distance: 20,
      features: JSON.stringify([
        'Rolls-Royce or Bentley',
        'Red carpet service',
        'Champagne on board',
        'Personal concierge',
        'VIP lounge access',
        'Priority lane',
        'Professional chauffeur',
        'Premium amenities',
      ]),
      amenities: JSON.stringify([
        'Luxury leather seats',
        'Entertainment system',
        'Champagne & refreshments',
        'WiFi',
        'Phone chargers',
        'Newspapers & magazines',
      ]),
      included: JSON.stringify([
        'VIP chauffeur',
        'All fees and taxes',
        'Meet & greet',
        'Champagne',
        'VIP lounge access',
        'Red carpet',
      ]),
      notIncluded: JSON.stringify(['Personal expenses', 'Gratuity']),
      images: JSON.stringify(['/images/transfers/vip-1.jpg']),
      mainImage: '/images/transfers/vip-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Rolls-Royce',
      vehicleModel: 'Phantom',
      vehicleYear: 2024,
      driverLanguages: JSON.stringify(['English', 'Arabic', 'French']),
      childSeat: true,
      wheelchairAccess: true,
      rating: 5.0,
      reviewCount: 42,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-group-van',
      slug: 'dubai-group-transfer-van',
      name: 'Group Transfer - Spacious Van',
      description: 'Perfect for groups and families. Spacious van with seating for up to 12 passengers and ample luggage space.',
      shortDescription: 'Group transfer for up to 12 passengers',
      transferType: TransferType.GROUP,
      vehicleType: VehicleType.VAN,
      fromLocation: 'Dubai International Airport (DXB)',
      toLocation: 'Dubai Hotels',
      maxPassengers: 12,
      maxLuggage: 12,
      price: 300,
      currency: 'AED',
      duration: 40,
      distance: 20,
      features: JSON.stringify([
        'Mercedes Sprinter or similar',
        'Seats up to 12 passengers',
        'Large luggage capacity',
        'Professional driver',
        'Air conditioning',
        'USB charging ports',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seating',
        'Large windows',
        'Storage space',
      ]),
      included: JSON.stringify(['Driver', 'Fuel', 'Tolls', 'Meet & greet']),
      notIncluded: JSON.stringify(['Gratuity', 'Extra stops']),
      images: JSON.stringify(['/images/transfers/van-1.jpg']),
      mainImage: '/images/transfers/van-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Mercedes-Benz',
      vehicleModel: 'Sprinter',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['English', 'Arabic']),
      childSeat: true,
      rating: 4.7,
      reviewCount: 87,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-private-driver-hourly',
      slug: 'dubai-private-driver-hourly',
      name: 'Private Driver - Hourly Service',
      description: 'Hire a private driver by the hour. Perfect for shopping, sightseeing, or business meetings. Flexible and convenient.',
      shortDescription: 'Private driver service by the hour',
      transferType: TransferType.PRIVATE_DRIVER,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Your Location',
      toLocation: 'Multiple Destinations',
      maxPassengers: 4,
      maxLuggage: 2,
      price: 150,
      pricePerHour: 150,
      currency: 'AED',
      features: JSON.stringify([
        'Professional driver',
        'Flexible itinerary',
        'Multiple stops',
        'Wait at each location',
        'Local knowledge',
        'Toyota Camry or similar',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Bottled water',
      ]),
      included: JSON.stringify(['Driver', 'Fuel', 'Parking', 'Tolls']),
      notIncluded: JSON.stringify(['Gratuity', 'Entrance fees']),
      images: JSON.stringify(['/images/transfers/private-driver-1.jpg']),
      mainImage: '/images/transfers/private-driver-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2024,
      driverLanguages: JSON.stringify(['English', 'Arabic', 'Hindi']),
      minBookingHours: 3,
      maxBookingHours: 12,
      rating: 4.8,
      reviewCount: 145,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-hotel-downtown',
      slug: 'dubai-hotel-downtown-transfer',
      name: 'Hotel Transfer - Downtown Dubai',
      description: 'Convenient hotel transfer to Downtown Dubai. Perfect for tourists visiting Burj Khalifa and Dubai Mall.',
      shortDescription: 'Hotel to Downtown Dubai transfer',
      transferType: TransferType.HOTEL,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Dubai Hotels',
      toLocation: 'Downtown Dubai',
      maxPassengers: 4,
      maxLuggage: 3,
      price: 100,
      currency: 'AED',
      duration: 25,
      distance: 15,
      features: JSON.stringify([
        'Comfortable sedan',
        'Professional driver',
        'Hotel pickup',
        'Air conditioning',
      ]),
      amenities: JSON.stringify(['Air conditioning', 'Clean vehicle', 'Bottled water']),
      included: JSON.stringify(['Driver', 'Fuel', 'Parking']),
      notIncluded: JSON.stringify(['Gratuity', 'Waiting time']),
      images: JSON.stringify(['/images/transfers/hotel-1.jpg']),
      mainImage: '/images/transfers/hotel-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['English', 'Arabic']),
      rating: 4.5,
      reviewCount: 76,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-airport-minibus',
      slug: 'dubai-airport-minibus-transfer',
      name: 'Airport Transfer - Minibus',
      description: 'Large group airport transfer with minibus. Ideal for corporate groups, tour groups, or large families.',
      shortDescription: 'Minibus airport transfer for large groups',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.MINIBUS,
      fromLocation: 'Dubai International Airport (DXB)',
      toLocation: 'Dubai Hotels',
      maxPassengers: 18,
      maxLuggage: 18,
      price: 450,
      currency: 'AED',
      duration: 45,
      distance: 25,
      features: JSON.stringify([
        'Minibus for up to 18 passengers',
        'Large luggage capacity',
        'Professional driver',
        'Air conditioning',
        'Comfortable seating',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Reclining seats',
        'Storage compartments',
      ]),
      included: JSON.stringify(['Driver', 'Fuel', 'Tolls', 'Meet & greet']),
      notIncluded: JSON.stringify(['Gratuity', 'Refreshments']),
      images: JSON.stringify(['/images/transfers/minibus-1.jpg']),
      mainImage: '/images/transfers/minibus-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Coaster',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['English', 'Arabic']),
      rating: 4.6,
      reviewCount: 54,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-city-luxury-suv',
      slug: 'dubai-city-luxury-suv',
      name: 'City Transfer - Luxury SUV',
      description: 'Premium city transfer in a luxury SUV. Perfect for business executives and VIP clients.',
      shortDescription: 'Luxury SUV for city transfers',
      transferType: TransferType.CITY,
      vehicleType: 'LUXURY',
      fromLocation: 'Business Bay',
      toLocation: 'Dubai Marina',
      maxPassengers: 5,
      maxLuggage: 4,
      price: 180,
      currency: 'AED',
      duration: 25,
      distance: 18,
      features: JSON.stringify([
        'Range Rover or similar',
        'Professional chauffeur',
        'Premium interior',
        'WiFi available',
        'Phone chargers',
        'Bottled water',
      ]),
      amenities: JSON.stringify([
        'Leather seats',
        'Climate control',
        'Entertainment system',
        'Privacy glass',
      ]),
      included: JSON.stringify(['Chauffeur', 'Fuel', 'Parking', 'Tolls']),
      notIncluded: JSON.stringify(['Gratuity', 'Waiting time']),
      images: JSON.stringify(['/images/transfers/luxury-suv-1.jpg']),
      mainImage: '/images/transfers/luxury-suv-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Land Rover',
      vehicleModel: 'Range Rover',
      vehicleYear: 2024,
      driverLanguages: JSON.stringify(['English', 'Arabic', 'French']),
      childSeat: true,
      wheelchairAccess: true,
      rating: 4.9,
      reviewCount: 112,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'transfer-airport-budget',
      slug: 'dubai-airport-budget-transfer',
      name: 'Budget Airport Transfer - Economy',
      description: 'Affordable airport transfer option. Clean, comfortable, and reliable service at the best price.',
      shortDescription: 'Budget-friendly airport transfer',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Dubai International Airport (DXB)',
      toLocation: 'Dubai City',
      maxPassengers: 3,
      maxLuggage: 2,
      price: 100,
      currency: 'AED',
      duration: 30,
      distance: 15,
      features: JSON.stringify([
        'Clean sedan (Nissan Sunny or similar)',
        'Professional driver',
        'Meet & greet',
        'Air conditioning',
      ]),
      amenities: JSON.stringify(['Air conditioning', 'Clean vehicle']),
      included: JSON.stringify(['Driver', 'Fuel', 'Tolls', 'Meet & greet']),
      notIncluded: JSON.stringify(['Gratuity', 'Waiting time beyond 30 min']),
      images: JSON.stringify(['/images/transfers/budget-1.jpg']),
      mainImage: '/images/transfers/budget-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      vehicleMake: 'Nissan',
      vehicleModel: 'Sunny',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['English', 'Arabic', 'Hindi']),
      rating: 4.4,
      reviewCount: 189,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const transfer of transfers) {
    await prisma.transfer.upsert({
      where: { id: transfer.id },
      update: transfer,
      create: transfer,
    });
    console.log(`✅ Created/Updated: ${transfer.name}`);
  }

  console.log('🎉 Transfer seeding completed!');
  console.log(`📊 Total transfers: ${transfers.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding transfers:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
