import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🏠 Starting Properties seeding...');

  const bangkok = await prisma.city.findFirst({ where: { name: 'Bangkok' } });
  const pattaya = await prisma.city.findFirst({ where: { name: 'Pattaya' } });
  const thailand = await prisma.country.findFirst({ where: { name: 'Thailand' } });

  if (!bangkok || !pattaya || !thailand) {
    throw new Error('Bangkok, Pattaya or Thailand not found. Please run seed-thailand.ts first.');
  }

  const properties = [
    // 1. Luxury Condo Bangkok
    {
      id: 'property-bangkok-luxury-condo-1',
      slug: 'luxury-condo-sukhumvit-bangkok',
      name: 'Luxury Condo in Sukhumvit',
      description: 'Modern luxury condominium in the heart of Sukhumvit, Bangkok. Fully furnished with stunning city views, close to BTS and shopping malls.',
      type: 'Condo',
      bedrooms: 2,
      bathrooms: 2,
      area: 85,
      floor: 25,
      furnished: true,
      pricePerNight: 3500,
      pricePerWeek: 21000,
      pricePerMonth: 75000,
      currency: 'THB',
      cityId: bangkok.id,
      countryId: thailand.id,
      address: 'Sukhumvit Road, Khlong Toei, Bangkok',
      latitude: 13.7307,
      longitude: 100.5418,
      features: JSON.stringify([
        'City View',
        'High Floor',
        'Near BTS',
        'Swimming Pool',
        'Gym',
        'Security 24/7',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Kitchen',
        'Washing Machine',
        'Parking',
      ]),
      images: JSON.stringify([
        '/images/properties/bangkok-condo-1.jpg',
        '/images/properties/bangkok-condo-2.jpg',
      ]),
      rating: 4.8,
      isFeatured: true,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 2. Beach Villa Pattaya
    {
      id: 'property-pattaya-beach-villa-1',
      slug: 'beach-villa-jomtien-pattaya',
      name: 'Beach Villa in Jomtien',
      description: 'Stunning beachfront villa in Jomtien, Pattaya. Private pool, direct beach access, perfect for families and groups.',
      type: 'Villa',
      bedrooms: 4,
      bathrooms: 3,
      area: 250,
      furnished: true,
      pricePerNight: 8500,
      pricePerWeek: 55000,
      pricePerMonth: 200000,
      currency: 'THB',
      cityId: pattaya.id,
      countryId: thailand.id,
      address: 'Jomtien Beach Road, Pattaya',
      latitude: 12.8836,
      longitude: 100.8825,
      features: JSON.stringify([
        'Beachfront',
        'Private Pool',
        'Sea View',
        'Garden',
        'BBQ Area',
        'Parking',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Full Kitchen',
        'Washing Machine',
        'Beach Chairs',
      ]),
      images: JSON.stringify([
        '/images/properties/pattaya-villa-1.jpg',
        '/images/properties/pattaya-villa-2.jpg',
      ]),
      rating: 4.9,
      isFeatured: true,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 3. Studio Bangkok
    {
      id: 'property-bangkok-studio-1',
      slug: 'modern-studio-asoke-bangkok',
      name: 'Modern Studio in Asoke',
      description: 'Cozy studio apartment in Asoke area, perfect for solo travelers or couples. Near MRT and shopping centers.',
      type: 'Studio',
      bedrooms: 1,
      bathrooms: 1,
      area: 35,
      floor: 15,
      furnished: true,
      pricePerNight: 1500,
      pricePerWeek: 9000,
      pricePerMonth: 30000,
      currency: 'THB',
      cityId: bangkok.id,
      countryId: thailand.id,
      address: 'Asoke, Watthana, Bangkok',
      latitude: 13.7367,
      longitude: 100.5608,
      features: JSON.stringify([
        'Near MRT',
        'Shopping Mall',
        'Swimming Pool',
        'Gym',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Kitchenette',
        'Microwave',
      ]),
      images: JSON.stringify([
        '/images/properties/bangkok-studio-1.jpg',
      ]),
      rating: 4.5,
      isFeatured: false,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 4. Penthouse Bangkok
    {
      id: 'property-bangkok-penthouse-1',
      slug: 'luxury-penthouse-sathorn-bangkok',
      name: 'Luxury Penthouse in Sathorn',
      description: 'Exclusive penthouse with panoramic Bangkok views. Top floor, private terrace, premium finishes throughout.',
      type: 'Penthouse',
      bedrooms: 3,
      bathrooms: 3,
      area: 180,
      floor: 45,
      furnished: true,
      pricePerNight: 12000,
      pricePerWeek: 75000,
      pricePerMonth: 280000,
      currency: 'THB',
      cityId: bangkok.id,
      countryId: thailand.id,
      address: 'Sathorn Road, Bangkok',
      latitude: 13.7245,
      longitude: 100.5282,
      features: JSON.stringify([
        'Panoramic View',
        'Private Terrace',
        'Top Floor',
        'Swimming Pool',
        'Gym',
        'Concierge',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'Smart TV',
        'Full Kitchen',
        'Wine Cooler',
        'Jacuzzi',
      ]),
      images: JSON.stringify([
        '/images/properties/bangkok-penthouse-1.jpg',
        '/images/properties/bangkok-penthouse-2.jpg',
      ]),
      rating: 5.0,
      isFeatured: true,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 5. House Pattaya
    {
      id: 'property-pattaya-house-1',
      slug: 'family-house-naklua-pattaya',
      name: 'Family House in Naklua',
      description: 'Spacious family house in quiet Naklua area. 3 bedrooms, garden, perfect for long-term stays.',
      type: 'House',
      bedrooms: 3,
      bathrooms: 2,
      area: 150,
      furnished: true,
      pricePerNight: 4500,
      pricePerWeek: 28000,
      pricePerMonth: 100000,
      currency: 'THB',
      cityId: pattaya.id,
      countryId: thailand.id,
      address: 'Naklua, Pattaya',
      latitude: 12.9636,
      longitude: 100.8925,
      features: JSON.stringify([
        'Garden',
        'Quiet Area',
        'Parking',
        'Near Beach',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Full Kitchen',
        'Washing Machine',
        'BBQ',
      ]),
      images: JSON.stringify([
        '/images/properties/pattaya-house-1.jpg',
      ]),
      rating: 4.6,
      isFeatured: false,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 6. Apartment Bangkok
    {
      id: 'property-bangkok-apartment-1',
      slug: 'cozy-apartment-thonglor-bangkok',
      name: 'Cozy Apartment in Thonglor',
      description: 'Trendy apartment in Thonglor, Bangkok\'s hippest neighborhood. Close to restaurants, bars, and nightlife.',
      type: 'Apartment',
      bedrooms: 1,
      bathrooms: 1,
      area: 45,
      floor: 10,
      furnished: true,
      pricePerNight: 2500,
      pricePerWeek: 15000,
      pricePerMonth: 50000,
      currency: 'THB',
      cityId: bangkok.id,
      countryId: thailand.id,
      address: 'Thonglor, Watthana, Bangkok',
      latitude: 13.7367,
      longitude: 100.5851,
      features: JSON.stringify([
        'Trendy Area',
        'Near BTS',
        'Restaurants',
        'Nightlife',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Kitchen',
        'Balcony',
      ]),
      images: JSON.stringify([
        '/images/properties/bangkok-apartment-1.jpg',
      ]),
      rating: 4.7,
      isFeatured: false,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 7. Condo Pattaya
    {
      id: 'property-pattaya-condo-1',
      slug: 'sea-view-condo-pratumnak-pattaya',
      name: 'Sea View Condo in Pratumnak',
      description: 'Beautiful sea view condominium on Pratumnak Hill. Quiet location with stunning views of Pattaya Bay.',
      type: 'Condo',
      bedrooms: 2,
      bathrooms: 2,
      area: 75,
      floor: 18,
      furnished: true,
      pricePerNight: 3000,
      pricePerWeek: 18000,
      pricePerMonth: 65000,
      currency: 'THB',
      cityId: pattaya.id,
      countryId: thailand.id,
      address: 'Pratumnak Hill, Pattaya',
      latitude: 12.9136,
      longitude: 100.8725,
      features: JSON.stringify([
        'Sea View',
        'Swimming Pool',
        'Gym',
        'Security',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Kitchen',
        'Balcony',
      ]),
      images: JSON.stringify([
        '/images/properties/pattaya-condo-1.jpg',
      ]),
      rating: 4.8,
      isFeatured: true,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 8. Townhouse Bangkok
    {
      id: 'property-bangkok-townhouse-1',
      slug: 'modern-townhouse-rama9-bangkok',
      name: 'Modern Townhouse in Rama 9',
      description: 'Contemporary townhouse in Rama 9 area. 3 floors, perfect for families, near MRT and shopping.',
      type: 'Townhouse',
      bedrooms: 3,
      bathrooms: 3,
      area: 120,
      furnished: true,
      pricePerNight: 5000,
      pricePerWeek: 32000,
      pricePerMonth: 120000,
      currency: 'THB',
      cityId: bangkok.id,
      countryId: thailand.id,
      address: 'Rama 9, Huai Khwang, Bangkok',
      latitude: 13.7594,
      longitude: 100.5648,
      features: JSON.stringify([
        '3 Floors',
        'Near MRT',
        'Parking',
        'Modern Design',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Full Kitchen',
        'Washing Machine',
      ]),
      images: JSON.stringify([
        '/images/properties/bangkok-townhouse-1.jpg',
      ]),
      rating: 4.6,
      isFeatured: false,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 9. Serviced Apartment Bangkok
    {
      id: 'property-bangkok-serviced-1',
      slug: 'serviced-apartment-silom-bangkok',
      name: 'Serviced Apartment in Silom',
      description: 'Premium serviced apartment in Silom business district. Daily housekeeping, concierge service, perfect for business travelers.',
      type: 'Serviced Apartment',
      bedrooms: 1,
      bathrooms: 1,
      area: 50,
      floor: 20,
      furnished: true,
      pricePerNight: 3500,
      pricePerWeek: 22000,
      pricePerMonth: 85000,
      currency: 'THB',
      cityId: bangkok.id,
      countryId: thailand.id,
      address: 'Silom Road, Bang Rak, Bangkok',
      latitude: 13.7278,
      longitude: 100.5282,
      features: JSON.stringify([
        'Daily Housekeeping',
        'Concierge',
        'Business Center',
        'Gym',
        'Pool',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Kitchenette',
        'Safe',
        'Minibar',
      ]),
      images: JSON.stringify([
        '/images/properties/bangkok-serviced-1.jpg',
      ]),
      rating: 4.9,
      isFeatured: true,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 10. Pool Villa Pattaya
    {
      id: 'property-pattaya-pool-villa-1',
      slug: 'private-pool-villa-east-pattaya',
      name: 'Private Pool Villa in East Pattaya',
      description: 'Exclusive pool villa in East Pattaya. Large private pool, tropical garden, complete privacy for your vacation.',
      type: 'Pool Villa',
      bedrooms: 3,
      bathrooms: 3,
      area: 200,
      furnished: true,
      pricePerNight: 7500,
      pricePerWeek: 48000,
      pricePerMonth: 180000,
      currency: 'THB',
      cityId: pattaya.id,
      countryId: thailand.id,
      address: 'East Pattaya',
      latitude: 12.9336,
      longitude: 100.9125,
      features: JSON.stringify([
        'Private Pool',
        'Tropical Garden',
        'Complete Privacy',
        'BBQ Area',
        'Parking',
      ]),
      amenities: JSON.stringify([
        'Air Conditioning',
        'WiFi',
        'TV',
        'Full Kitchen',
        'Washing Machine',
        'Pool Equipment',
      ]),
      images: JSON.stringify([
        '/images/properties/pattaya-pool-villa-1.jpg',
        '/images/properties/pattaya-pool-villa-2.jpg',
      ]),
      rating: 5.0,
      isFeatured: true,
      isAvailable: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const property of properties) {
    await prisma.property.upsert({
      where: { id: property.id },
      update: property,
      create: property,
    });
    console.log(`✅ Created/Updated: ${property.name} - ${property.currency} ${property.pricePerNight}/night`);
  }

  console.log('🎉 Properties seeding completed!');
  console.log(`📊 Total properties: ${properties.length}`);
  console.log('💰 All prices in THB (Thai Baht)');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding properties:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
