import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🏥 Starting Doctors seeding...\n');

  // Get Dubai city
  const dubai = await prisma.city.findFirst({
    where: { slug: 'dubai' },
  });

  if (!dubai) {
    console.error('❌ Dubai city not found. Please seed cities first.');
    return;
  }

  const doctors = [
    {
      id: `doctor-${Date.now()}-1`,
      slug: 'dr-ahmed-hassan-cardiology',
      firstName: 'Ahmed',
      lastName: 'Hassan',
      title: 'Dr.',
      gender: 'Male',
      photo: '👨‍⚕️',
      specialty: 'Cardiology',
      subSpecialties: JSON.stringify(['Interventional Cardiology', 'Heart Failure', 'Preventive Cardiology']),
      licenseNumber: 'DXB-CARD-2024-001',
      yearsOfExperience: 15,
      education: JSON.stringify([
        'MD - Cairo University, Egypt',
        'Fellowship in Cardiology - Johns Hopkins, USA',
        'Board Certified - American Board of Internal Medicine'
      ]),
      certifications: JSON.stringify(['ABIM Cardiology', 'FACC', 'FESC']),
      languages: JSON.stringify(['Arabic', 'English', 'French']),
      clinicName: 'Dubai Heart Center',
      clinicAddress: 'Healthcare City, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 500,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Aetna', 'AXA']),
      workingDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      workingHours: JSON.stringify({ start: '09:00', end: '17:00' }),
      consultationDuration: 30,
      breakTime: JSON.stringify({ start: '13:00', end: '14:00' }),
      services: JSON.stringify([
        'ECG', 'Echocardiography', 'Stress Test', 'Holter Monitoring',
        'Cardiac Catheterization', 'Angioplasty', 'Pacemaker Implantation'
      ]),
      treatmentAreas: JSON.stringify([
        'Coronary Artery Disease', 'Heart Failure', 'Arrhythmias',
        'Hypertension', 'Valvular Heart Disease', 'Congenital Heart Disease'
      ]),
      phone: '+971-4-XXX-XXXX',
      email: 'dr.ahmed.hassan@dubaiheart.ae',
      whatsapp: '+971-50-XXX-XXXX',
      website: 'www.dubaiheart.ae',
      rating: 4.9,
      reviewCount: 127,
      totalPatients: 1500,
      totalAppointments: 3200,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: true,
      metaTitle: 'Dr. Ahmed Hassan - Cardiologist in Dubai',
      metaDescription: 'Expert cardiologist with 15+ years experience. Specialized in interventional cardiology and heart failure treatment.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `doctor-${Date.now()}-2`,
      slug: 'dr-sarah-johnson-dermatology',
      firstName: 'Sarah',
      lastName: 'Johnson',
      title: 'Dr.',
      gender: 'Female',
      photo: '👩‍⚕️',
      specialty: 'Dermatology',
      subSpecialties: JSON.stringify(['Cosmetic Dermatology', 'Pediatric Dermatology', 'Dermatologic Surgery']),
      licenseNumber: 'DXB-DERM-2024-002',
      yearsOfExperience: 12,
      education: JSON.stringify([
        'MD - University of London, UK',
        'Residency in Dermatology - Harvard Medical School, USA',
        'Fellowship in Cosmetic Dermatology - UCLA, USA'
      ]),
      certifications: JSON.stringify(['ABD', 'FAAD', 'Laser Certification']),
      languages: JSON.stringify(['English', 'Arabic']),
      clinicName: 'Dubai Skin Clinic',
      clinicAddress: 'Jumeirah, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 400,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Bupa']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']),
      workingHours: JSON.stringify({ start: '10:00', end: '18:00' }),
      consultationDuration: 20,
      breakTime: JSON.stringify({ start: '14:00', end: '15:00' }),
      services: JSON.stringify([
        'Acne Treatment', 'Laser Hair Removal', 'Botox & Fillers',
        'Chemical Peels', 'Skin Cancer Screening', 'Mole Removal'
      ]),
      treatmentAreas: JSON.stringify([
        'Acne', 'Eczema', 'Psoriasis', 'Skin Cancer', 'Aging Skin',
        'Hair Loss', 'Pigmentation', 'Rosacea'
      ]),
      phone: '+971-4-YYY-YYYY',
      email: 'dr.sarah.johnson@dubaiskin.ae',
      whatsapp: '+971-50-YYY-YYYY',
      website: 'www.dubaiskin.ae',
      rating: 4.8,
      reviewCount: 98,
      totalPatients: 1200,
      totalAppointments: 2500,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: false,
      metaTitle: 'Dr. Sarah Johnson - Dermatologist in Dubai',
      metaDescription: 'Expert dermatologist specializing in cosmetic and medical dermatology. 12+ years experience.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `doctor-${Date.now()}-3`,
      slug: 'dr-mohammed-ali-pediatrics',
      firstName: 'Mohammed',
      lastName: 'Ali',
      title: 'Dr.',
      gender: 'Male',
      photo: '👨‍⚕️',
      specialty: 'Pediatrics',
      subSpecialties: JSON.stringify(['Neonatology', 'Pediatric Cardiology', 'Developmental Pediatrics']),
      licenseNumber: 'DXB-PED-2024-003',
      yearsOfExperience: 18,
      education: JSON.stringify([
        'MD - American University of Beirut, Lebanon',
        'Pediatric Residency - Boston Children\'s Hospital, USA',
        'Fellowship in Neonatology - Stanford, USA'
      ]),
      certifications: JSON.stringify(['ABP', 'FAAP', 'NRP', 'PALS']),
      languages: JSON.stringify(['Arabic', 'English']),
      clinicName: 'Dubai Children\'s Clinic',
      clinicAddress: 'Dubai Marina, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 350,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Aetna', 'Bupa', 'AXA']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      workingHours: JSON.stringify({ start: '08:00', end: '16:00' }),
      consultationDuration: 30,
      breakTime: JSON.stringify({ start: '12:00', end: '13:00' }),
      services: JSON.stringify([
        'Well-Child Visits', 'Vaccinations', 'Growth Monitoring',
        'Developmental Assessment', 'Sick Visits', 'Newborn Care'
      ]),
      treatmentAreas: JSON.stringify([
        'Respiratory Infections', 'Allergies', 'Asthma', 'Growth Disorders',
        'Behavioral Issues', 'Newborn Jaundice', 'Feeding Problems'
      ]),
      phone: '+971-4-ZZZ-ZZZZ',
      email: 'dr.mohammed.ali@dubaichildren.ae',
      whatsapp: '+971-50-ZZZ-ZZZZ',
      website: 'www.dubaichildren.ae',
      rating: 4.9,
      reviewCount: 156,
      totalPatients: 2000,
      totalAppointments: 4500,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: true,
      metaTitle: 'Dr. Mohammed Ali - Pediatrician in Dubai',
      metaDescription: 'Experienced pediatrician with 18+ years caring for children. Specialized in neonatology and pediatric cardiology.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `doctor-${Date.now()}-4`,
      slug: 'dr-fatima-khan-obstetrics-gynecology',
      firstName: 'Fatima',
      lastName: 'Khan',
      title: 'Dr.',
      gender: 'Female',
      photo: '👩‍⚕️',
      specialty: 'Obstetrics & Gynecology',
      subSpecialties: JSON.stringify(['High-Risk Pregnancy', 'Gynecologic Oncology', 'Reproductive Endocrinology']),
      licenseNumber: 'DXB-OBGYN-2024-004',
      yearsOfExperience: 14,
      education: JSON.stringify([
        'MD - King Saud University, Saudi Arabia',
        'OB/GYN Residency - Mayo Clinic, USA',
        'Fellowship in Maternal-Fetal Medicine - Yale, USA'
      ]),
      certifications: JSON.stringify(['ABOG', 'FACOG', 'MFM Subspecialty']),
      languages: JSON.stringify(['Arabic', 'English', 'Urdu']),
      clinicName: 'Dubai Women\'s Health Center',
      clinicAddress: 'Jumeirah Lake Towers, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 450,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Bupa', 'AXA']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']),
      workingHours: JSON.stringify({ start: '09:00', end: '17:00' }),
      consultationDuration: 30,
      breakTime: JSON.stringify({ start: '13:00', end: '14:00' }),
      services: JSON.stringify([
        'Prenatal Care', 'High-Risk Pregnancy Management', 'Ultrasound',
        'Gynecologic Surgery', 'Fertility Consultation', 'Menopause Management'
      ]),
      treatmentAreas: JSON.stringify([
        'Pregnancy Complications', 'Infertility', 'PCOS', 'Endometriosis',
        'Fibroids', 'Ovarian Cysts', 'Menstrual Disorders'
      ]),
      phone: '+971-4-AAA-AAAA',
      email: 'dr.fatima.khan@dubaiwomen.ae',
      whatsapp: '+971-50-AAA-AAAA',
      website: 'www.dubaiwomen.ae',
      rating: 4.9,
      reviewCount: 142,
      totalPatients: 1800,
      totalAppointments: 3500,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: true,
      metaTitle: 'Dr. Fatima Khan - OB/GYN in Dubai',
      metaDescription: 'Expert obstetrician and gynecologist specializing in high-risk pregnancies. 14+ years experience.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `doctor-${Date.now()}-5`,
      slug: 'dr-james-wilson-orthopedics',
      firstName: 'James',
      lastName: 'Wilson',
      title: 'Dr.',
      gender: 'Male',
      photo: '👨‍⚕️',
      specialty: 'Orthopedics',
      subSpecialties: JSON.stringify(['Sports Medicine', 'Joint Replacement', 'Spine Surgery']),
      licenseNumber: 'DXB-ORTHO-2024-005',
      yearsOfExperience: 16,
      education: JSON.stringify([
        'MD - University of Sydney, Australia',
        'Orthopedic Residency - Hospital for Special Surgery, USA',
        'Fellowship in Sports Medicine - Cleveland Clinic, USA'
      ]),
      certifications: JSON.stringify(['ABOS', 'CAQ Sports Medicine', 'Arthroscopy Certification']),
      languages: JSON.stringify(['English', 'Arabic']),
      clinicName: 'Dubai Orthopedic & Sports Medicine Center',
      clinicAddress: 'Dubai Sports City, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 500,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Aetna', 'Bupa']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']),
      workingHours: JSON.stringify({ start: '08:00', end: '16:00' }),
      consultationDuration: 30,
      breakTime: JSON.stringify({ start: '12:00', end: '13:00' }),
      services: JSON.stringify([
        'Joint Replacement', 'Arthroscopy', 'Sports Injury Treatment',
        'Fracture Care', 'Spine Surgery', 'Physical Therapy'
      ]),
      treatmentAreas: JSON.stringify([
        'Knee Injuries', 'Shoulder Problems', 'Back Pain', 'Sports Injuries',
        'Arthritis', 'Fractures', 'Ligament Tears'
      ]),
      phone: '+971-4-BBB-BBBB',
      email: 'dr.james.wilson@dubaiortho.ae',
      whatsapp: '+971-50-BBB-BBBB',
      website: 'www.dubaiortho.ae',
      rating: 4.8,
      reviewCount: 89,
      totalPatients: 1100,
      totalAppointments: 2200,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: false,
      metaTitle: 'Dr. James Wilson - Orthopedic Surgeon in Dubai',
      metaDescription: 'Expert orthopedic surgeon specializing in sports medicine and joint replacement. 16+ years experience.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // DENTISTES
    {
      id: `doctor-${Date.now()}-6`,
      slug: 'dr-layla-mahmoud-dentistry',
      firstName: 'Layla',
      lastName: 'Mahmoud',
      title: 'Dr.',
      gender: 'Female',
      photo: '👩‍⚕️',
      specialty: 'Dentistry',
      subSpecialties: JSON.stringify(['Cosmetic Dentistry', 'Orthodontics', 'Implantology']),
      licenseNumber: 'DXB-DENT-2024-006',
      yearsOfExperience: 10,
      education: JSON.stringify([
        'DDS - University of Damascus, Syria',
        'Advanced Cosmetic Dentistry - NYU, USA',
        'Implantology Certification - ITI, Switzerland'
      ]),
      certifications: JSON.stringify(['DDS', 'Invisalign Certified', 'Implant Specialist']),
      languages: JSON.stringify(['Arabic', 'English', 'French']),
      clinicName: 'Dubai Smile Dental Clinic',
      clinicAddress: 'Dubai Marina, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 300,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Bupa', 'AXA']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']),
      workingHours: JSON.stringify({ start: '09:00', end: '18:00' }),
      consultationDuration: 30,
      breakTime: JSON.stringify({ start: '13:00', end: '14:00' }),
      services: JSON.stringify([
        'Teeth Whitening', 'Veneers', 'Dental Implants', 'Invisalign',
        'Root Canal', 'Crowns & Bridges', 'Gum Treatment'
      ]),
      treatmentAreas: JSON.stringify([
        'Cosmetic Dentistry', 'Orthodontics', 'Implants', 'General Dentistry',
        'Periodontics', 'Endodontics', 'Preventive Care'
      ]),
      phone: '+971-4-CCC-CCCC',
      email: 'dr.layla.mahmoud@dubaismile.ae',
      whatsapp: '+971-50-CCC-CCCC',
      website: 'www.dubaismile.ae',
      rating: 4.9,
      reviewCount: 134,
      totalPatients: 1600,
      totalAppointments: 3100,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: false,
      metaTitle: 'Dr. Layla Mahmoud - Dentist in Dubai',
      metaDescription: 'Expert cosmetic dentist specializing in smile makeovers, veneers, and dental implants. 10+ years experience.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `doctor-${Date.now()}-7`,
      slug: 'dr-omar-rashid-orthodontics',
      firstName: 'Omar',
      lastName: 'Rashid',
      title: 'Dr.',
      gender: 'Male',
      photo: '👨‍⚕️',
      specialty: 'Orthodontics',
      subSpecialties: JSON.stringify(['Invisalign', 'Braces', 'Pediatric Orthodontics']),
      licenseNumber: 'DXB-ORTHO-2024-007',
      yearsOfExperience: 13,
      education: JSON.stringify([
        'DDS - King Abdulaziz University, Saudi Arabia',
        'Orthodontics Residency - University of Michigan, USA',
        'Invisalign Master Certification'
      ]),
      certifications: JSON.stringify(['Orthodontics Specialist', 'Invisalign Diamond Provider', 'Damon System Certified']),
      languages: JSON.stringify(['Arabic', 'English']),
      clinicName: 'Dubai Orthodontic Center',
      clinicAddress: 'Business Bay, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 350,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Aetna', 'Bupa']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      workingHours: JSON.stringify({ start: '10:00', end: '19:00' }),
      consultationDuration: 45,
      breakTime: JSON.stringify({ start: '14:00', end: '15:00' }),
      services: JSON.stringify([
        'Invisalign', 'Metal Braces', 'Ceramic Braces', 'Lingual Braces',
        'Retainers', 'Early Orthodontic Treatment', 'Adult Orthodontics'
      ]),
      treatmentAreas: JSON.stringify([
        'Malocclusion', 'Crowded Teeth', 'Gaps', 'Overbite', 'Underbite',
        'Crossbite', 'TMJ Disorders'
      ]),
      phone: '+971-4-DDD-DDDD',
      email: 'dr.omar.rashid@dubaiortho.ae',
      whatsapp: '+971-50-DDD-DDDD',
      website: 'www.dubaiortho.ae',
      rating: 4.8,
      reviewCount: 112,
      totalPatients: 1400,
      totalAppointments: 2800,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: true,
      metaTitle: 'Dr. Omar Rashid - Orthodontist in Dubai',
      metaDescription: 'Expert orthodontist specializing in Invisalign and braces for all ages. 13+ years experience.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `doctor-${Date.now()}-8`,
      slug: 'dr-nina-patel-pediatric-dentistry',
      firstName: 'Nina',
      lastName: 'Patel',
      title: 'Dr.',
      gender: 'Female',
      photo: '👩‍⚕️',
      specialty: 'Pediatric Dentistry',
      subSpecialties: JSON.stringify(['Children Dentistry', 'Preventive Care', 'Sedation Dentistry']),
      licenseNumber: 'DXB-PEDDENT-2024-008',
      yearsOfExperience: 11,
      education: JSON.stringify([
        'DDS - University of Mumbai, India',
        'Pediatric Dentistry Residency - Boston University, USA',
        'Sedation Dentistry Certification'
      ]),
      certifications: JSON.stringify(['Pediatric Dentistry Specialist', 'Sedation Certified', 'Laser Dentistry']),
      languages: JSON.stringify(['English', 'Hindi', 'Arabic']),
      clinicName: 'Kids Dental Care Dubai',
      clinicAddress: 'Jumeirah Beach Residence, Dubai',
      cityId: dubai.id,
      countryId: dubai.countryId,
      consultationFee: 280,
      acceptsInsurance: true,
      insuranceProviders: JSON.stringify(['Daman', 'Cigna', 'Bupa', 'AXA', 'Aetna']),
      workingDays: JSON.stringify(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']),
      workingHours: JSON.stringify({ start: '09:00', end: '17:00' }),
      consultationDuration: 30,
      breakTime: JSON.stringify({ start: '13:00', end: '14:00' }),
      services: JSON.stringify([
        'Preventive Care', 'Fluoride Treatment', 'Dental Sealants',
        'Cavity Fillings', 'Pulp Therapy', 'Sedation Dentistry', 'Emergency Care'
      ]),
      treatmentAreas: JSON.stringify([
        'Tooth Decay', 'Gum Disease', 'Dental Trauma', 'Thumb Sucking',
        'Early Orthodontic Issues', 'Tooth Eruption Problems'
      ]),
      phone: '+971-4-EEE-EEEE',
      email: 'dr.nina.patel@kidsdental.ae',
      whatsapp: '+971-50-EEE-EEEE',
      website: 'www.kidsdental.ae',
      rating: 4.9,
      reviewCount: 167,
      totalPatients: 1900,
      totalAppointments: 3800,
      isVerified: true,
      isPremium: true,
      acceptsOnlineBooking: true,
      acceptsVideoConsult: false,
      metaTitle: 'Dr. Nina Patel - Pediatric Dentist in Dubai',
      metaDescription: 'Caring pediatric dentist specializing in children\'s dental care. Gentle approach with 11+ years experience.',
      isActive: true,
      isAcceptingPatients: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const doctor of doctors) {
    await prisma.doctor.upsert({
      where: { slug: doctor.slug },
      update: doctor,
      create: doctor,
    });
    console.log(`✅ Created/Updated: ${doctor.firstName} ${doctor.lastName} (${doctor.specialty})`);
  }

  console.log(`\n🎉 Successfully seeded ${doctors.length} doctors and dentists!`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding doctors:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
