import { PrismaClient, TransferType, VehicleType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🚕 Starting Thailand transfer seeding...');

  const bangkok = await prisma.city.findFirst({ where: { name: 'Bangkok' } });
  const pattaya = await prisma.city.findFirst({ where: { name: 'Pattaya' } });
  const thailand = await prisma.country.findFirst({ where: { name: 'Thailand' } });

  if (!bangkok || !pattaya || !thailand) {
    throw new Error('Bangkok, Pattaya or Thailand not found. Please run seed-thailand.ts first.');
  }

  // Delete old Dubai transfers
  await prisma.transfer.deleteMany({});
  console.log('🗑️  Deleted old transfers');

  const transfers = [
    // 1. Bangkok to Pattaya - 1,199 THB
    {
      id: 'transfer-bangkok-pattaya-taxi',
      slug: 'bangkok-to-pattaya-taxi',
      name: 'Bangkok to Pattaya - Taxi Service',
      description: 'Comfortable taxi transfer from Bangkok to Pattaya. Professional driver, air-conditioned vehicle, door-to-door service. Perfect for travelers heading to Pattaya beach resort.',
      shortDescription: 'Bangkok to Pattaya taxi transfer',
      transferType: TransferType.CITY,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Bangkok',
      toLocation: 'Pattaya',
      fromAddress: 'Any location in Bangkok',
      toAddress: 'Any location in Pattaya',
      maxPassengers: 3,
      maxLuggage: 3,
      price: 1199,
      currency: 'THB',
      duration: 120,
      distance: 147,
      features: JSON.stringify([
        'Professional driver',
        'Air conditioning',
        'Door-to-door service',
        'Comfortable sedan',
        'Highway tolls included',
        'Bottled water',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Clean vehicle',
        'Comfortable seats',
        'Trunk space',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
        'Parking fees',
        'Bottled water',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Extra stops',
        'Waiting time',
      ]),
      images: JSON.stringify(['/images/transfers/bangkok-pattaya.jpg']),
      mainImage: '/images/transfers/bangkok-pattaya-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 2,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      rating: 4.7,
      reviewCount: 234,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 2. Pattaya to Bangkok Airport - 1,199 THB
    {
      id: 'transfer-pattaya-bangkok-airport',
      slug: 'pattaya-to-bangkok-airport-taxi',
      name: 'Pattaya to Bangkok Airport (BKK) - Taxi',
      description: 'Direct taxi transfer from Pattaya to Suvarnabhumi Airport (BKK). Flight tracking, meet & greet, comfortable ride to catch your flight on time.',
      shortDescription: 'Pattaya to Bangkok Airport taxi',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Pattaya',
      toLocation: 'Suvarnabhumi Airport (BKK)',
      fromAddress: 'Any hotel in Pattaya',
      toAddress: 'Suvarnabhumi Airport, Bangkok',
      maxPassengers: 3,
      maxLuggage: 3,
      price: 1199,
      currency: 'THB',
      duration: 120,
      distance: 147,
      features: JSON.stringify([
        'Flight tracking',
        'Meet & greet',
        'Professional driver',
        'Air conditioning',
        'Highway tolls included',
        'On-time guarantee',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Large trunk',
        'Phone charger',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
        'Parking fees',
        'Flight tracking',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Airport parking (if waiting)',
      ]),
      images: JSON.stringify(['/images/transfers/pattaya-airport.jpg']),
      mainImage: '/images/transfers/pattaya-airport-main.jpg',
      cityId: pattaya.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 3,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      rating: 4.8,
      reviewCount: 189,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 3. Bangkok to Suvarnabhumi Airport - 799 THB
    {
      id: 'transfer-bangkok-suvarnabhumi',
      slug: 'bangkok-to-suvarnabhumi-airport-taxi',
      name: 'Bangkok to Suvarnabhumi Airport - Taxi',
      description: 'Affordable taxi transfer from Bangkok city to Suvarnabhumi Airport. Reliable service, professional driver, fixed price with no hidden fees.',
      shortDescription: 'Bangkok to BKK Airport taxi',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Bangkok City',
      toLocation: 'Suvarnabhumi Airport (BKK)',
      fromAddress: 'Any location in Bangkok',
      toAddress: 'Suvarnabhumi Airport',
      maxPassengers: 3,
      maxLuggage: 2,
      price: 799,
      currency: 'THB',
      duration: 45,
      distance: 30,
      features: JSON.stringify([
        'Professional driver',
        'Air conditioning',
        'Fixed price',
        'No hidden fees',
        'Highway tolls included',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Clean vehicle',
        'Comfortable seats',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
        'Parking fees',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Waiting time',
      ]),
      images: JSON.stringify(['/images/transfers/bangkok-airport.jpg']),
      mainImage: '/images/transfers/bangkok-airport-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Altis',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 2,
      cancellationPolicy: 'Free cancellation up to 12 hours before pickup',
      rating: 4.6,
      reviewCount: 456,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 4. Pattaya to U-Tapao Airport - 899 THB
    {
      id: 'transfer-pattaya-utapao',
      slug: 'pattaya-to-utapao-airport-taxi',
      name: 'Pattaya to U-Tapao Airport - Taxi',
      description: 'Quick and convenient taxi transfer from Pattaya to U-Tapao Airport. Short distance, professional service, perfect for flights from U-Tapao.',
      shortDescription: 'Pattaya to U-Tapao Airport taxi',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Pattaya',
      toLocation: 'U-Tapao Airport (UTP)',
      fromAddress: 'Any hotel in Pattaya',
      toAddress: 'U-Tapao Rayong-Pattaya International Airport',
      maxPassengers: 3,
      maxLuggage: 3,
      price: 899,
      currency: 'THB',
      duration: 40,
      distance: 35,
      features: JSON.stringify([
        'Professional driver',
        'Air conditioning',
        'Short distance',
        'Quick transfer',
        'Flight tracking',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Trunk space',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Parking fees',
        'Flight tracking',
      ]),
      notIncluded: JSON.stringify([
        'Highway tolls (if any)',
        'Gratuity',
      ]),
      images: JSON.stringify(['/images/transfers/pattaya-utapao.jpg']),
      mainImage: '/images/transfers/pattaya-utapao-main.jpg',
      cityId: pattaya.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Vios',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 2,
      cancellationPolicy: 'Free cancellation up to 12 hours before pickup',
      rating: 4.7,
      reviewCount: 123,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 5. Suvarnabhumi Airport to Bangkok - Economy
    {
      id: 'transfer-suvarnabhumi-bangkok-economy',
      slug: 'suvarnabhumi-airport-to-bangkok-economy',
      name: 'Suvarnabhumi Airport to Bangkok - Economy Sedan',
      description: 'Budget-friendly airport transfer from Suvarnabhumi to Bangkok city. Clean vehicle, professional driver, great value for money.',
      shortDescription: 'BKK Airport to Bangkok - Economy',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Suvarnabhumi Airport (BKK)',
      toLocation: 'Bangkok City',
      fromAddress: 'Suvarnabhumi Airport',
      toAddress: 'Any location in Bangkok',
      maxPassengers: 3,
      maxLuggage: 2,
      price: 750,
      currency: 'THB',
      duration: 45,
      distance: 30,
      features: JSON.stringify([
        'Professional driver',
        'Air conditioning',
        'Budget-friendly',
        'Clean vehicle',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Clean vehicle',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Waiting time',
      ]),
      images: JSON.stringify(['/images/transfers/airport-bangkok.jpg']),
      mainImage: '/images/transfers/airport-bangkok-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Vios',
      vehicleYear: 2022,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 2,
      cancellationPolicy: 'Free cancellation up to 12 hours before pickup',
      rating: 4.5,
      reviewCount: 312,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 6. Bangkok to Pattaya - Van (6 seater)
    {
      id: 'transfer-bangkok-pattaya-van',
      slug: 'bangkok-to-pattaya-van-6-seater',
      name: 'Bangkok to Pattaya - Van (6 Seater)',
      description: 'Spacious van transfer from Bangkok to Pattaya for families and groups. Comfortable seating for up to 6 passengers with luggage space.',
      shortDescription: 'Bangkok to Pattaya - Van for groups',
      transferType: TransferType.CITY,
      vehicleType: VehicleType.VAN,
      fromLocation: 'Bangkok',
      toLocation: 'Pattaya',
      maxPassengers: 6,
      maxLuggage: 6,
      price: 1799,
      currency: 'THB',
      duration: 120,
      distance: 147,
      features: JSON.stringify([
        'Spacious van',
        'Professional driver',
        'Air conditioning',
        'Extra luggage space',
        'Highway tolls included',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Large storage',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
        'Parking fees',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Extra stops',
      ]),
      images: JSON.stringify(['/images/transfers/van-bangkok-pattaya.jpg']),
      mainImage: '/images/transfers/van-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Commuter',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 3,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      rating: 4.8,
      reviewCount: 167,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 7. Suvarnabhumi Airport to Pattaya - Direct
    {
      id: 'transfer-suvarnabhumi-pattaya',
      slug: 'suvarnabhumi-airport-to-pattaya-direct',
      name: 'Suvarnabhumi Airport to Pattaya - Direct Transfer',
      description: 'Direct transfer from Suvarnabhumi Airport to Pattaya. Skip the hassle, professional driver will meet you at arrivals and take you directly to your hotel.',
      shortDescription: 'BKK Airport to Pattaya - Direct',
      transferType: TransferType.AIRPORT,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Suvarnabhumi Airport (BKK)',
      toLocation: 'Pattaya',
      fromAddress: 'Suvarnabhumi Airport',
      toAddress: 'Any hotel in Pattaya',
      maxPassengers: 3,
      maxLuggage: 3,
      price: 1399,
      currency: 'THB',
      duration: 120,
      distance: 147,
      features: JSON.stringify([
        'Meet & greet at arrivals',
        'Flight tracking',
        'Professional driver',
        'Air conditioning',
        'Highway tolls included',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Trunk space',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
        'Meet & greet',
        'Flight tracking',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
      ]),
      images: JSON.stringify(['/images/transfers/airport-pattaya.jpg']),
      mainImage: '/images/transfers/airport-pattaya-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 3,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      rating: 4.9,
      reviewCount: 278,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 8. Bangkok City Tour - Private Driver
    {
      id: 'transfer-bangkok-private-driver',
      slug: 'bangkok-private-driver-hourly',
      name: 'Bangkok Private Driver - Hourly Service',
      description: 'Hire a private driver in Bangkok by the hour. Perfect for shopping, sightseeing, or business meetings. Flexible itinerary, local knowledge.',
      shortDescription: 'Bangkok private driver by the hour',
      transferType: TransferType.PRIVATE_DRIVER,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Bangkok',
      toLocation: 'Multiple Destinations',
      maxPassengers: 3,
      maxLuggage: 2,
      price: 500,
      pricePerHour: 500,
      currency: 'THB',
      features: JSON.stringify([
        'Flexible itinerary',
        'Local knowledge',
        'Multiple stops',
        'Wait at each location',
        'Professional driver',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Bottled water',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Parking fees',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Entrance fees',
        'Highway tolls',
      ]),
      images: JSON.stringify(['/images/transfers/private-driver.jpg']),
      mainImage: '/images/transfers/private-driver-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Altis',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English', 'Chinese']),
      minBookingHours: 4,
      maxBookingHours: 12,
      advanceBooking: 1,
      cancellationPolicy: 'Free cancellation up to 6 hours before service',
      rating: 4.7,
      reviewCount: 201,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 9. Pattaya to Bangkok - Luxury SUV
    {
      id: 'transfer-pattaya-bangkok-luxury-suv',
      slug: 'pattaya-to-bangkok-luxury-suv',
      name: 'Pattaya to Bangkok - Luxury SUV',
      description: 'Premium SUV transfer from Pattaya to Bangkok. Spacious, comfortable, perfect for business travelers or those seeking extra comfort.',
      shortDescription: 'Pattaya to Bangkok - Luxury SUV',
      transferType: TransferType.CITY,
      vehicleType: VehicleType.LUXURY,
      fromLocation: 'Pattaya',
      toLocation: 'Bangkok',
      maxPassengers: 4,
      maxLuggage: 4,
      price: 1999,
      currency: 'THB',
      duration: 120,
      distance: 147,
      features: JSON.stringify([
        'Luxury SUV',
        'Professional chauffeur',
        'WiFi available',
        'Phone chargers',
        'Bottled water',
        'Highway tolls included',
      ]),
      amenities: JSON.stringify([
        'Leather seats',
        'Climate control',
        'Entertainment system',
        'Privacy glass',
      ]),
      included: JSON.stringify([
        'Chauffeur',
        'Fuel',
        'Highway tolls',
        'Parking fees',
        'WiFi',
        'Refreshments',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
      ]),
      images: JSON.stringify(['/images/transfers/luxury-suv.jpg']),
      mainImage: '/images/transfers/luxury-suv-main.jpg',
      cityId: pattaya.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Alphard',
      vehicleYear: 2024,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      childSeat: true,
      wheelchairAccess: true,
      advanceBooking: 3,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      rating: 4.9,
      reviewCount: 89,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // 10. Bangkok to Hua Hin
    {
      id: 'transfer-bangkok-huahin',
      slug: 'bangkok-to-hua-hin-taxi',
      name: 'Bangkok to Hua Hin - Taxi Service',
      description: 'Comfortable taxi transfer from Bangkok to Hua Hin beach resort. Professional driver, air-conditioned vehicle, scenic coastal route.',
      shortDescription: 'Bangkok to Hua Hin taxi',
      transferType: TransferType.CITY,
      vehicleType: VehicleType.SEDAN,
      fromLocation: 'Bangkok',
      toLocation: 'Hua Hin',
      maxPassengers: 3,
      maxLuggage: 3,
      price: 2199,
      currency: 'THB',
      duration: 180,
      distance: 200,
      features: JSON.stringify([
        'Professional driver',
        'Air conditioning',
        'Scenic route',
        'Highway tolls included',
        'Bottled water',
      ]),
      amenities: JSON.stringify([
        'Air conditioning',
        'Comfortable seats',
        'Trunk space',
      ]),
      included: JSON.stringify([
        'Driver',
        'Fuel',
        'Highway tolls',
        'Parking fees',
      ]),
      notIncluded: JSON.stringify([
        'Gratuity',
        'Extra stops',
      ]),
      images: JSON.stringify(['/images/transfers/bangkok-huahin.jpg']),
      mainImage: '/images/transfers/bangkok-huahin-main.jpg',
      cityId: bangkok.id,
      countryId: thailand.id,
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      vehicleYear: 2023,
      driverLanguages: JSON.stringify(['Thai', 'English']),
      advanceBooking: 3,
      cancellationPolicy: 'Free cancellation up to 24 hours before pickup',
      rating: 4.6,
      reviewCount: 145,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const transfer of transfers) {
    await prisma.transfer.upsert({
      where: { id: transfer.id },
      update: transfer,
      create: transfer,
    });
    console.log(`✅ Created/Updated: ${transfer.name} - ${transfer.currency} ${transfer.price}`);
  }

  console.log('🎉 Thailand transfer seeding completed!');
  console.log(`📊 Total transfers: ${transfers.length}`);
  console.log('💰 All prices in THB (Thai Baht)');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding Thailand transfers:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
