import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🎯 Starting Activities seeding...');

  // Get Thailand and cities
  const thailand = await prisma.country.findFirst({ where: { code: 'TH' } });
  const bangkok = await prisma.city.findFirst({ where: { slug: 'bangkok' } });
  const pattaya = await prisma.city.findFirst({ where: { slug: 'pattaya' } });
  const phuket = await prisma.city.findFirst({ where: { slug: 'phuket' } });

  // Get UAE and Dubai
  const uae = await prisma.country.findFirst({ where: { code: 'AE' } });
  const dubai = await prisma.city.findFirst({ where: { slug: 'dubai' } });

  if (!thailand || !uae) {
    console.error('❌ Countries not found. Please run seed-thailand and seed-dubai first.');
    return;
  }

  // Thailand Activities
  const thailandActivities = [
    // Bangkok Activities
    {
      id: 'activity-bangkok-temple-tour',
      name: 'Grand Palace & Temples Tour',
      slug: 'grand-palace-temples-tour-bangkok',
      description: 'Explore Bangkok\'s most iconic temples including the Grand Palace, Wat Pho (Temple of the Reclining Buddha), and Wat Arun (Temple of Dawn). This full-day guided tour takes you through the rich history and stunning architecture of Thailand\'s most sacred sites.',
      category: 'Cultural',
      duration: '8 hours',
      minAge: 5,
      maxGroupSize: 15,
      difficulty: 'Easy',
      pricePerPerson: 2500,
      currency: 'THB',
      cityId: bangkok?.id || 'city-bangkok',
      countryId: thailand.id,
      meetingPoint: 'Grand Palace Main Entrance',
      latitude: 13.7500,
      longitude: 100.4913,
      included: JSON.stringify(['Professional English-speaking guide', 'Temple entrance fees', 'Bottled water', 'Hotel pickup and drop-off', 'Air-conditioned vehicle']),
      notIncluded: JSON.stringify(['Lunch', 'Personal expenses', 'Tips (optional)']),
      whatToBring: JSON.stringify(['Comfortable walking shoes', 'Modest clothing (shoulders and knees covered)', 'Sunscreen', 'Camera', 'Hat']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['08:00', '09:00', '13:00']),
      images: JSON.stringify(['/media/activities/cultural/grand-palace.svg', '/media/activities/cultural/wat-pho.svg', '/media/activities/cultural/wat-arun.svg']),
      rating: 4.8,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-bangkok-floating-market',
      name: 'Damnoen Saduak Floating Market',
      slug: 'floating-market-tour-bangkok',
      description: 'Experience the vibrant atmosphere of Thailand\'s most famous floating market. Watch vendors sell fresh fruits, vegetables, and local delicacies from traditional wooden boats. Includes a long-tail boat ride through the canals.',
      category: 'Cultural',
      duration: '6 hours',
      minAge: 3,
      maxGroupSize: 20,
      difficulty: 'Easy',
      pricePerPerson: 1800,
      currency: 'THB',
      cityId: bangkok?.id || 'city-bangkok',
      countryId: thailand.id,
      meetingPoint: 'Hotel Lobby',
      latitude: 13.5200,
      longitude: 99.9600,
      included: JSON.stringify(['Hotel pickup and drop-off', 'Long-tail boat ride', 'English-speaking guide', 'Bottled water']),
      notIncluded: JSON.stringify(['Food and drinks', 'Personal shopping', 'Tips']),
      whatToBring: JSON.stringify(['Camera', 'Cash (Thai Baht)', 'Sunscreen', 'Hat', 'Comfortable shoes']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['06:00', '07:00']),
      images: JSON.stringify(['/media/activities/cultural/floating-market.svg', '/media/activities/cultural/boat-market.svg']),
      rating: 4.6,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-bangkok-cooking-class',
      name: 'Thai Cooking Class & Market Tour',
      slug: 'thai-cooking-class-bangkok',
      description: 'Learn to cook authentic Thai dishes in this hands-on cooking class. Start with a visit to a local market to select fresh ingredients, then prepare 5-6 traditional dishes under expert guidance. Take home recipes and new skills!',
      category: 'Food & Drink',
      duration: '5 hours',
      minAge: 10,
      maxGroupSize: 12,
      difficulty: 'Easy',
      pricePerPerson: 2200,
      currency: 'THB',
      cityId: bangkok?.id || 'city-bangkok',
      countryId: thailand.id,
      meetingPoint: 'Cooking School',
      latitude: 13.7400,
      longitude: 100.5300,
      included: JSON.stringify(['Market tour', 'All ingredients', 'Recipe booklet', 'Lunch (dishes you prepare)', 'Apron', 'Certificate']),
      notIncluded: JSON.stringify(['Hotel transfer', 'Drinks']),
      whatToBring: JSON.stringify(['Camera', 'Appetite', 'Comfortable clothes']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      startTimes: JSON.stringify(['09:00', '14:00']),
      images: JSON.stringify(['/media/activities/food-drink/cooking-class.svg', '/media/activities/food-drink/thai-food.svg']),
      rating: 4.9,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },

    // Pattaya Activities
    {
      id: 'activity-pattaya-coral-island',
      name: 'Coral Island Snorkeling & Beach Day',
      slug: 'coral-island-pattaya',
      description: 'Escape to the pristine Coral Island (Koh Larn) for a day of snorkeling, swimming, and beach relaxation. Crystal-clear waters, white sandy beaches, and vibrant marine life await you just 45 minutes from Pattaya.',
      category: 'Water Sports',
      duration: '7 hours',
      minAge: 6,
      maxGroupSize: 30,
      difficulty: 'Easy',
      pricePerPerson: 1500,
      currency: 'THB',
      cityId: pattaya?.id || 'city-pattaya',
      countryId: thailand.id,
      meetingPoint: 'Pattaya Beach Pier',
      latitude: 12.9236,
      longitude: 100.8825,
      included: JSON.stringify(['Speedboat transfer', 'Snorkeling equipment', 'Life jacket', 'Lunch', 'Drinking water', 'Insurance']),
      notIncluded: JSON.stringify(['Beach chair rental', 'Water activities', 'Personal expenses']),
      whatToBring: JSON.stringify(['Swimwear', 'Towel', 'Sunscreen', 'Change of clothes', 'Waterproof bag']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['08:00', '09:00', '10:00']),
      images: JSON.stringify(['/media/activities/water-sports/coral-island.svg', '/media/activities/water-sports/snorkeling.svg']),
      rating: 4.7,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-pattaya-parasailing',
      name: 'Parasailing Adventure',
      slug: 'parasailing-pattaya',
      description: 'Soar high above Pattaya Bay and enjoy breathtaking aerial views of the coastline. This thrilling parasailing experience is perfect for adventure seekers and offers unforgettable photo opportunities.',
      category: 'Adventure',
      duration: '1 hour',
      minAge: 12,
      maxGroupSize: 2,
      difficulty: 'Moderate',
      pricePerPerson: 800,
      currency: 'THB',
      cityId: pattaya?.id || 'city-pattaya',
      countryId: thailand.id,
      meetingPoint: 'Pattaya Beach Water Sports Center',
      latitude: 12.9300,
      longitude: 100.8800,
      included: JSON.stringify(['Parasailing equipment', 'Safety briefing', 'Life jacket', 'Insurance', 'Photos']),
      notIncluded: JSON.stringify(['Hotel transfer', 'Video recording']),
      whatToBring: JSON.stringify(['Swimwear', 'Sunglasses', 'Sunscreen', 'Waterproof camera']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['09:00', '10:00', '11:00', '13:00', '14:00', '15:00', '16:00']),
      images: JSON.stringify(['/media/activities/adventure/parasailing.svg', '/media/activities/adventure/pattaya-beach.svg']),
      rating: 4.5,
      isFeatured: false,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },

    // Phuket Activities
    {
      id: 'activity-phuket-phi-phi-island',
      name: 'Phi Phi Islands Day Trip',
      slug: 'phi-phi-islands-phuket',
      description: 'Discover the stunning Phi Phi Islands on this full-day speedboat tour. Visit Maya Bay (The Beach movie location), snorkel in crystal-clear waters, explore Viking Cave, and relax on pristine beaches.',
      category: 'Island Hopping',
      duration: '9 hours',
      minAge: 4,
      maxGroupSize: 35,
      difficulty: 'Easy',
      pricePerPerson: 3200,
      currency: 'THB',
      cityId: phuket?.id || 'city-phuket',
      countryId: thailand.id,
      meetingPoint: 'Phuket Pier',
      latitude: 7.8804,
      longitude: 98.3923,
      included: JSON.stringify(['Speedboat transfer', 'National park fees', 'Snorkeling equipment', 'Lunch', 'Soft drinks', 'English guide', 'Insurance']),
      notIncluded: JSON.stringify(['Hotel transfer (available for extra fee)', 'Underwater camera rental']),
      whatToBring: JSON.stringify(['Swimwear', 'Towel', 'Sunscreen', 'Camera', 'Light jacket', 'Motion sickness medicine']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['07:00', '08:00']),
      images: JSON.stringify(['/media/activities/island-hopping/phi-phi.svg', '/media/activities/island-hopping/maya-bay.svg', '/media/activities/island-hopping/snorkel-phi-phi.svg']),
      rating: 4.9,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
  ];

  // Dubai Activities
  const dubaiActivities = [
    {
      id: 'activity-dubai-desert-safari',
      name: 'Desert Safari with BBQ Dinner',
      slug: 'desert-safari-dubai',
      description: 'Experience the ultimate Arabian adventure! Enjoy dune bashing in a 4x4, camel riding, sandboarding, henna painting, and a delicious BBQ dinner under the stars with live entertainment including belly dancing and Tanoura shows.',
      category: 'Adventure',
      duration: '6 hours',
      minAge: 3,
      maxGroupSize: 6,
      difficulty: 'Moderate',
      pricePerPerson: 250,
      currency: 'AED',
      cityId: dubai?.id || 'city-dubai',
      countryId: uae.id,
      meetingPoint: 'Hotel Pickup',
      latitude: 25.0657,
      longitude: 55.1713,
      included: JSON.stringify(['Hotel pickup and drop-off', 'Dune bashing', 'Camel ride', 'Sandboarding', 'BBQ dinner', 'Live shows', 'Unlimited soft drinks', 'Henna painting']),
      notIncluded: JSON.stringify(['Quad biking (extra charge)', 'Alcoholic beverages', 'Shisha smoking']),
      whatToBring: JSON.stringify(['Sunglasses', 'Sunscreen', 'Camera', 'Light jacket for evening', 'Comfortable shoes']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['15:00', '15:30']),
      images: JSON.stringify(['/media/activities/adventure/desert-safari.svg', '/media/activities/adventure/dune-bashing.svg', '/media/activities/adventure/bbq-dinner.svg']),
      rating: 4.8,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-dubai-burj-khalifa',
      name: 'Burj Khalifa At The Top SKY',
      slug: 'burj-khalifa-sky-dubai',
      description: 'Visit the world\'s tallest building! Skip the line and ascend to levels 124, 125, and 148 of Burj Khalifa. Enjoy panoramic views of Dubai from the highest observation deck in the world at 555 meters.',
      category: 'Sightseeing',
      duration: '2 hours',
      minAge: 4,
      maxGroupSize: 50,
      difficulty: 'Easy',
      pricePerPerson: 450,
      currency: 'AED',
      cityId: dubai?.id || 'city-dubai',
      countryId: uae.id,
      meetingPoint: 'Burj Khalifa Entrance',
      latitude: 25.1972,
      longitude: 55.2744,
      included: JSON.stringify(['Skip-the-line access', 'Access to levels 124, 125 & 148', 'Multimedia presentation', 'Refreshments at SKY lounge', 'Telescope viewing']),
      notIncluded: JSON.stringify(['Hotel transfer', 'Food and drinks', 'Souvenirs']),
      whatToBring: JSON.stringify(['Camera', 'Valid ID', 'Comfortable shoes']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00']),
      images: JSON.stringify(['/media/activities/sightseeing/burj-khalifa.svg', '/media/activities/sightseeing/dubai-view.svg']),
      rating: 4.9,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-dubai-dhow-cruise',
      name: 'Dubai Marina Dhow Cruise Dinner',
      slug: 'dhow-cruise-dinner-dubai',
      description: 'Sail along Dubai Marina on a traditional wooden dhow while enjoying a delicious international buffet dinner. Experience stunning views of the illuminated skyline, modern architecture, and luxury yachts.',
      category: 'Dinner Cruise',
      duration: '2 hours',
      minAge: 2,
      maxGroupSize: 100,
      difficulty: 'Easy',
      pricePerPerson: 180,
      currency: 'AED',
      cityId: dubai?.id || 'city-dubai',
      countryId: uae.id,
      meetingPoint: 'Dubai Marina Pier',
      latitude: 25.0800,
      longitude: 55.1400,
      included: JSON.stringify(['2-hour cruise', 'International buffet dinner', 'Welcome drinks', 'Live entertainment', 'Background music', 'Air-conditioned lower deck']),
      notIncluded: JSON.stringify(['Hotel transfer (available for extra)', 'Alcoholic beverages', 'VIP seating']),
      whatToBring: JSON.stringify(['Camera', 'Light jacket', 'Comfortable clothes']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['20:00', '20:30']),
      images: JSON.stringify(['/media/activities/dinner-cruise/dhow-cruise.svg', '/media/activities/dinner-cruise/dubai-marina.svg']),
      rating: 4.7,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-dubai-aquarium',
      name: 'Dubai Aquarium & Underwater Zoo',
      slug: 'dubai-aquarium-underwater-zoo',
      description: 'Explore one of the world\'s largest suspended aquariums located in Dubai Mall. Walk through the 48-meter tunnel surrounded by thousands of aquatic animals including sharks and rays. Visit the Underwater Zoo on Level 2.',
      category: 'Family',
      duration: '3 hours',
      minAge: 0,
      maxGroupSize: 100,
      difficulty: 'Easy',
      pricePerPerson: 150,
      currency: 'AED',
      cityId: dubai?.id || 'city-dubai',
      countryId: uae.id,
      meetingPoint: 'Dubai Mall - Aquarium Entrance',
      latitude: 25.1975,
      longitude: 55.2796,
      included: JSON.stringify(['Aquarium tunnel access', 'Underwater Zoo access', 'Interactive displays', 'Educational presentations']),
      notIncluded: JSON.stringify(['Cage snorkeling', 'Shark dive', 'Glass-bottom boat ride', 'Behind-the-scenes tour']),
      whatToBring: JSON.stringify(['Camera', 'Comfortable shoes', 'Water bottle']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00']),
      images: JSON.stringify(['/media/activities/family/dubai-aquarium.svg', '/media/activities/family/underwater-zoo.svg']),
      rating: 4.6,
      isFeatured: false,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
    {
      id: 'activity-dubai-skydive',
      name: 'Skydive Dubai - Palm Drop Zone',
      slug: 'skydive-dubai-palm',
      description: 'Experience the ultimate adrenaline rush with a tandem skydive over the iconic Palm Jumeirah! Freefall from 13,000 feet and enjoy breathtaking views of Dubai\'s coastline. Professional instructors ensure a safe and unforgettable experience.',
      category: 'Extreme Sports',
      duration: '4 hours',
      minAge: 18,
      maxGroupSize: 1,
      difficulty: 'Extreme',
      pricePerPerson: 2199,
      currency: 'AED',
      cityId: dubai?.id || 'city-dubai',
      countryId: uae.id,
      meetingPoint: 'Skydive Dubai - Palm Dropzone',
      latitude: 25.1124,
      longitude: 55.1390,
      included: JSON.stringify(['Tandem skydive', 'Professional instructor', 'All equipment', 'Training session', 'Certificate', 'Insurance']),
      notIncluded: JSON.stringify(['Video and photos package', 'Hotel transfer', 'T-shirt']),
      whatToBring: JSON.stringify(['Valid ID/Passport', 'Athletic shoes', 'Comfortable clothes', 'Sunglasses']),
      availableDays: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      startTimes: JSON.stringify(['07:00', '08:00', '09:00', '10:00']),
      images: JSON.stringify(['/media/activities/extreme-sports/skydive-dubai.svg', '/media/activities/extreme-sports/palm-jumeirah.svg']),
      rating: 5.0,
      isFeatured: true,
      isActive: true,
      isAvailable: true,
      updatedAt: new Date(),
    },
  ];

  // Create all activities
  const allActivities = [...thailandActivities, ...dubaiActivities];

  for (const activity of allActivities) {
    await prisma.activity.upsert({
      where: { id: activity.id },
      update: activity,
      create: activity,
    });
    console.log(`✅ Created/Updated: ${activity.name}`);
  }

  console.log(`\n🎉 Successfully seeded ${allActivities.length} activities!`);
  console.log(`   - Thailand: ${thailandActivities.length} activities`);
  console.log(`   - Dubai: ${dubaiActivities.length} activities`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding activities:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
