import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🚤 Starting yacht seeding...');

  const dubai = await prisma.city.findFirst({ where: { name: 'Dubai' } });
  const uae = await prisma.country.findFirst({ where: { name: 'United Arab Emirates' } });

  if (!dubai || !uae) {
    throw new Error('Dubai or UAE not found. Please run seed-dubai.ts first.');
  }

  const yachts = [
    {
      id: 'yacht-lamborghini-63',
      slug: 'lamborghini-yacht-63',
      name: 'Lamborghini Yacht 63',
      brand: 'LAMBORGHINI',
      model: 'Tecnomar 63',
      year: 2024,
      length: 63,
      capacity: 12,
      cabins: 2,
      bathrooms: 2,
      crew: 3,
      pricePerHour: 5000,
      priceFor2Hours: 9500,
      priceFor4Hours: 18000,
      pricePerDay: 80000,
      currency: 'AED',
      description: 'Experience ultimate luxury with the Lamborghini Yacht 63. Italian craftsmanship meets cutting-edge technology.',
      shortDescription: 'Luxury Italian yacht with supercar-inspired design',
      features: JSON.stringify(['Carbon fiber hull', 'Twin MAN V12 engines', 'Top speed 60 knots', 'Premium sound system']),
      amenities: JSON.stringify(['Sun deck', 'Dining area', 'Wet bar', 'Swimming platform', 'Water toys']),
      included: JSON.stringify(['Professional crew', 'Fuel', 'Soft drinks', 'Towels', 'Safety equipment']),
      notIncluded: JSON.stringify(['Food and catering', 'Alcoholic beverages', 'Water sports', 'Gratuity']),
      images: JSON.stringify(['/images/yachts/lamborghini-1.jpg']),
      mainImage: '/images/yachts/lamborghini-main.jpg',
      location: 'Dubai Marina',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 60,
      fuelType: 'Diesel',
      engineType: 'Twin MAN V12',
      manufacturer: 'Tecnomar',
      rating: 4.9,
      reviewCount: 47,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-sunseeker-88',
      slug: 'sunseeker-88-yacht',
      name: 'Sunseeker 88 Yacht',
      brand: 'SUNSEEKER',
      year: 2023,
      length: 88,
      capacity: 20,
      cabins: 4,
      crew: 4,
      pricePerHour: 4500,
      priceFor4Hours: 16000,
      pricePerDay: 70000,
      currency: 'AED',
      description: 'British yacht design masterpiece with spacious decks and luxurious cabins.',
      shortDescription: 'British luxury yacht with spacious decks',
      features: JSON.stringify(['Flybridge with Jacuzzi', 'Spacious salon', '4 luxury cabins', 'Entertainment system']),
      amenities: JSON.stringify(['Jacuzzi', 'BBQ grill', 'Dining for 12', 'Swim platform', 'Water toys']),
      included: JSON.stringify(['Crew (4)', 'Fuel', 'Soft drinks', 'Towels']),
      notIncluded: JSON.stringify(['Catering', 'Alcohol', 'Jet skis', 'Gratuity']),
      images: JSON.stringify(['/images/yachts/sunseeker-1.jpg']),
      mainImage: '/images/yachts/sunseeker-main.jpg',
      location: 'Dubai Marina',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 30,
      rating: 4.8,
      reviewCount: 62,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-azimut-70',
      slug: 'azimut-70-flybridge',
      name: 'Azimut 70 Flybridge',
      brand: 'AZIMUT',
      year: 2023,
      length: 70,
      capacity: 16,
      cabins: 3,
      crew: 3,
      pricePerHour: 3500,
      priceFor4Hours: 12000,
      pricePerDay: 50000,
      currency: 'AED',
      description: 'Italian elegance meets modern comfort. Perfect for family gatherings and corporate events.',
      features: JSON.stringify(['Spacious flybridge', 'Modern interior', '3 cabins', 'WiFi']),
      amenities: JSON.stringify(['Flybridge seating', 'Dining area', 'Sun deck', 'Water toys']),
      included: JSON.stringify(['Crew', 'Fuel', 'Soft drinks', 'Towels']),
      notIncluded: JSON.stringify(['Food', 'Alcohol', 'Gratuity']),
      images: JSON.stringify(['/images/yachts/azimut-1.jpg']),
      mainImage: '/images/yachts/azimut-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 28,
      rating: 4.7,
      reviewCount: 38,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-majesty-48',
      slug: 'majesty-48-flybridge',
      name: 'Majesty 48 Flybridge',
      brand: 'MAJESTY',
      year: 2024,
      length: 48,
      capacity: 12,
      cabins: 2,
      crew: 2,
      pricePerHour: 1500,
      priceFor4Hours: 5200,
      pricePerDay: 22000,
      currency: 'AED',
      description: 'Excellent value for money. Perfect for small groups.',
      features: JSON.stringify(['Flybridge', 'Comfortable salon', '2 cabins', 'Air conditioning']),
      amenities: JSON.stringify(['Sun deck', 'Dining area', 'Swim platform']),
      included: JSON.stringify(['Crew', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Food', 'Alcohol']),
      images: JSON.stringify(['/images/yachts/majesty-1.jpg']),
      mainImage: '/images/yachts/majesty-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 25,
      rating: 4.6,
      reviewCount: 29,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-ferretti-550',
      slug: 'ferretti-550-flybridge',
      name: 'Ferretti 550 Flybridge',
      brand: 'FERRETTI',
      year: 2022,
      length: 55,
      capacity: 14,
      cabins: 3,
      crew: 2,
      pricePerHour: 2200,
      priceFor4Hours: 7500,
      pricePerDay: 32000,
      currency: 'AED',
      description: 'Perfect blend of performance and comfort. Italian craftsmanship.',
      features: JSON.stringify(['Spacious flybridge', 'Modern interior', '3 cabins', 'WiFi']),
      amenities: JSON.stringify(['Flybridge seating', 'Dining area', 'Water toys']),
      included: JSON.stringify(['Crew', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Catering', 'Alcohol']),
      images: JSON.stringify(['/images/yachts/ferretti-1.jpg']),
      mainImage: '/images/yachts/ferretti-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 30,
      rating: 4.7,
      reviewCount: 41,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-princess-60',
      slug: 'princess-60-flybridge',
      name: 'Princess 60 Flybridge',
      brand: 'PRINCESS',
      year: 2023,
      length: 60,
      capacity: 15,
      cabins: 3,
      crew: 3,
      pricePerHour: 2800,
      priceFor4Hours: 9800,
      pricePerDay: 40000,
      currency: 'AED',
      description: 'British elegance and superior comfort.',
      features: JSON.stringify(['Large flybridge', 'Luxury interior', '3 cabins', 'WiFi']),
      amenities: JSON.stringify(['Flybridge dining', 'Sun deck', 'Water toys']),
      included: JSON.stringify(['Crew', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Food', 'Alcohol']),
      images: JSON.stringify(['/images/yachts/princess-1.jpg']),
      mainImage: '/images/yachts/princess-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 32,
      rating: 4.8,
      reviewCount: 53,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-pershing-70',
      slug: 'pershing-70-sport',
      name: 'Pershing 70 Sport',
      brand: 'PERSHING',
      year: 2024,
      length: 70,
      capacity: 12,
      cabins: 3,
      crew: 3,
      pricePerHour: 4000,
      priceFor4Hours: 14000,
      pricePerDay: 60000,
      currency: 'AED',
      description: 'High-performance sport yacht. Speed and luxury combined.',
      features: JSON.stringify(['Sport design', 'High-speed', '3 cabins', 'WiFi']),
      amenities: JSON.stringify(['Sun deck', 'Dining area', 'Water toys']),
      included: JSON.stringify(['Crew', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Catering', 'Jet skis']),
      images: JSON.stringify(['/images/yachts/pershing-1.jpg']),
      mainImage: '/images/yachts/pershing-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 45,
      rating: 4.9,
      reviewCount: 35,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-riva-76',
      slug: 'riva-76-bahamas',
      name: 'Riva 76 Bahamas',
      brand: 'RIVA',
      year: 2023,
      length: 76,
      capacity: 18,
      cabins: 4,
      crew: 4,
      pricePerHour: 4200,
      priceFor4Hours: 15000,
      pricePerDay: 62000,
      currency: 'AED',
      description: 'Icon of Italian style. Timeless elegance meets modern luxury.',
      features: JSON.stringify(['Iconic design', 'Spacious decks', '4 cabins', 'WiFi']),
      amenities: JSON.stringify(['Large sun deck', 'Dining for 12', 'Water toys']),
      included: JSON.stringify(['Crew (4)', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Catering', 'Alcohol']),
      images: JSON.stringify(['/images/yachts/riva-1.jpg']),
      mainImage: '/images/yachts/riva-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 35,
      rating: 4.9,
      reviewCount: 44,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-benetti-100',
      slug: 'benetti-100-tradition',
      name: 'Benetti 100 Tradition',
      brand: 'BENETTI',
      year: 2022,
      length: 100,
      capacity: 24,
      cabins: 5,
      crew: 6,
      pricePerHour: 6000,
      priceFor4Hours: 22000,
      pricePerDay: 95000,
      currency: 'AED',
      description: 'Epitome of luxury. Perfect for large events and weddings.',
      features: JSON.stringify(['Spacious decks', 'Luxury salon', '5 cabins', 'Jacuzzi', 'WiFi']),
      amenities: JSON.stringify(['Jacuzzi', 'Sun deck', 'Dining for 20', 'BBQ', 'Water toys']),
      included: JSON.stringify(['Crew (6)', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Catering', 'Jet skis']),
      images: JSON.stringify(['/images/yachts/benetti-1.jpg']),
      mainImage: '/images/yachts/benetti-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 28,
      rating: 5.0,
      reviewCount: 28,
      isFeatured: true,
      minBookingHours: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'yacht-gulf-craft-36',
      slug: 'gulf-craft-36-touring',
      name: 'Gulf Craft 36 Touring',
      brand: 'GULF CRAFT',
      year: 2024,
      length: 36,
      capacity: 8,
      cabins: 1,
      crew: 2,
      pricePerHour: 800,
      priceFor4Hours: 2800,
      pricePerDay: 12000,
      currency: 'AED',
      description: 'Budget-friendly option for small groups and families.',
      features: JSON.stringify(['Comfortable cabin', 'Basic amenities', 'Air conditioning']),
      amenities: JSON.stringify(['Sun deck', 'Swim platform', 'Basic water toys']),
      included: JSON.stringify(['Crew', 'Fuel', 'Soft drinks']),
      notIncluded: JSON.stringify(['Food', 'Alcohol']),
      images: JSON.stringify(['/images/yachts/gulfcraft-1.jpg']),
      mainImage: '/images/yachts/gulfcraft-main.jpg',
      cityId: dubai.id,
      countryId: uae.id,
      speed: 22,
      rating: 4.5,
      reviewCount: 18,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const yacht of yachts) {
    await prisma.yacht.upsert({
      where: { id: yacht.id },
      update: yacht,
      create: yacht,
    });
    console.log(`✅ Created/Updated: ${yacht.name}`);
  }

  console.log('🎉 Yacht seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding yachts:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
