import { PrismaClient, PropertyStatus, PropertyType, PropertyVisibility } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🏠 Starting complete properties seed (RENT, SALE, OFF-PLAN)...');

  // Get cities
  const bangkok = await prisma.city.findFirst({ where: { slug: 'bangkok' } });
  const pattaya = await prisma.city.findFirst({ where: { slug: 'pattaya' } });
  const phuket = await prisma.city.findFirst({ where: { slug: 'phuket' } });
  const dubai = await prisma.city.findFirst({ where: { slug: 'dubai' } });

  if (!bangkok || !pattaya || !phuket || !dubai) {
    throw new Error('Cities not found. Please run seed-base-geography first.');
  }

  // Get countries
  const thailand = await prisma.country.findFirst({ where: { code: 'TH' } });
  const uae = await prisma.country.findFirst({ where: { code: 'AE' } });

  // Get currencies
  const thb = await prisma.currency.findFirst({ where: { code: 'THB' } });
  const aed = await prisma.currency.findFirst({ where: { code: 'AED' } });

  const properties = [
    // ========================================
    // THAILAND - BANGKOK - LOCATION (RENT)
    // ========================================
    {
      slug: 'condo-asoke-bangkok-rent',
      title: 'Modern Condo at Asoke Intersection',
      subtitle: '2BR High Floor with BTS Access',
      description: 'Prime location condo at Asoke intersection. 2 bedrooms, 2 bathrooms on high floor with stunning city views. Walking distance to BTS Asoke and MRT Sukhumvit. Fully furnished with modern appliances, gym, pool, and 24/7 security.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: '88 Sukhumvit 21 (Asoke)',
      addressLine2: 'Khlong Toei Nuea, Watthana',
      cityId: bangkok.id,
      countryId: thailand.id,
      latitude: 13.7380,
      longitude: 100.5607,
      bedrooms: 2,
      bathrooms: 2,
      parkingSpaces: 1,
      areaSize: 75,
      areaUnit: 'sqm',
      yearBuilt: 2021,
      price: 65000,
      priceCurrencyId: thb?.id,
      pricePostfix: '/month',
      rentalDetails: {
        deposit: 130000,
        minimumStay: '1 year',
        utilities: 'Extra',
        internet: 'Included',
      },
      publishedAt: new Date(),
    },
    {
      slug: 'riverside-condo-bangkok-rent',
      title: 'Chao Phraya Riverside Condo',
      subtitle: 'River View 1BR Luxury',
      description: 'Exclusive riverside condominium with breathtaking Chao Phraya River views. 1 bedroom, 1 bathroom with floor-to-ceiling windows. Access to riverside pool, gym, and shuttle boat service. Perfect for expats.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Charoen Krung Road',
      addressLine2: 'Bang Rak',
      cityId: bangkok.id,
      countryId: thailand.id,
      latitude: 13.7267,
      longitude: 100.5143,
      bedrooms: 1,
      bathrooms: 1,
      parkingSpaces: 1,
      areaSize: 55,
      areaUnit: 'sqm',
      yearBuilt: 2020,
      price: 48000,
      priceCurrencyId: thb?.id,
      pricePostfix: '/month',
      publishedAt: new Date(),
    },

    // ========================================
    // THAILAND - BANGKOK - VENTE (SALE)
    // ========================================
    {
      slug: 'penthouse-sathorn-bangkok-sale',
      title: 'Luxurious Penthouse in Sathorn',
      subtitle: '3BR Penthouse with Private Pool',
      description: 'Ultra-luxury 3-bedroom penthouse in prime Sathorn area. Private rooftop pool, 360° Bangkok views, premium Italian marble finishes. 2 parking spaces, maid room. Freehold ownership available for foreigners (with Thai company).',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'South Sathorn Road',
      addressLine2: 'Sathorn, Yan Nawa',
      cityId: bangkok.id,
      countryId: thailand.id,
      latitude: 13.7197,
      longitude: 100.5326,
      bedrooms: 3,
      bathrooms: 3,
      parkingSpaces: 2,
      areaSize: 250,
      areaUnit: 'sqm',
      yearBuilt: 2019,
      price: 35000000,
      priceCurrencyId: thb?.id,
      publishedAt: new Date(),
    },
    {
      slug: 'townhouse-ramintra-bangkok-sale',
      title: 'Modern Townhouse Ramintra',
      subtitle: '3BR Townhouse Ready to Move',
      description: '3-bedroom townhouse in secure gated community in Ramintra area. 3 floors, 2 parking spaces, small garden. Close to schools, shopping malls, and expressway. Perfect for families.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: false,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Ramintra Road',
      addressLine2: 'Khan Na Yao',
      cityId: bangkok.id,
      countryId: thailand.id,
      latitude: 13.8247,
      longitude: 100.6478,
      bedrooms: 3,
      bathrooms: 3,
      parkingSpaces: 2,
      areaSize: 180,
      areaUnit: 'sqm',
      landArea: 35,
      landAreaUnit: 'sqw',
      yearBuilt: 2022,
      price: 7500000,
      priceCurrencyId: thb?.id,
      publishedAt: new Date(),
    },

    // ========================================
    // THAILAND - PATTAYA - LOCATION (RENT)
    // ========================================
    {
      slug: 'seaview-condo-wongamat-pattaya-rent',
      title: 'Sea View Condo in Wongamat Beach',
      subtitle: '2BR Direct Sea View',
      description: 'Beautiful 2-bedroom condo with direct sea view in exclusive Wongamat Beach area. Fully furnished, infinity pool, gym, and private beach access. Quiet area yet close to Central Pattaya.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Wongamat Beach',
      addressLine2: 'Naklua, Bang Lamung',
      cityId: pattaya.id,
      countryId: thailand.id,
      latitude: 12.9536,
      longitude: 100.8895,
      bedrooms: 2,
      bathrooms: 2,
      parkingSpaces: 1,
      areaSize: 88,
      areaUnit: 'sqm',
      yearBuilt: 2020,
      price: 48000,
      priceCurrencyId: thb?.id,
      pricePostfix: '/month',
      publishedAt: new Date(),
    },

    // ========================================
    // THAILAND - PATTAYA - VENTE (SALE)
    // ========================================
    {
      slug: 'villa-phoenix-golf-pattaya-sale',
      title: 'Golf Course Villa in Phoenix Golf',
      subtitle: '4BR Villa on Golf Course',
      description: 'Stunning 4-bedroom villa overlooking Phoenix Golf Course. Private pool, tropical garden, 3 parking spaces. Freehold in Thai company name. Perfect for golfers and families.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Phoenix Golf Course',
      addressLine2: 'Huay Yai, Bang Lamung',
      cityId: pattaya.id,
      countryId: thailand.id,
      latitude: 12.8653,
      longitude: 100.9256,
      bedrooms: 4,
      bathrooms: 4,
      parkingSpaces: 3,
      areaSize: 320,
      areaUnit: 'sqm',
      landArea: 120,
      landAreaUnit: 'sqw',
      yearBuilt: 2018,
      price: 18500000,
      priceCurrencyId: thb?.id,
      publishedAt: new Date(),
    },
    {
      slug: 'condo-viewtalay-jomtien-sale',
      title: 'View Talay Condo Jomtien',
      subtitle: '1BR Investment Condo',
      description: 'Affordable 1-bedroom condo in popular View Talay complex. Sea view, fully furnished, great for rental income. Foreign quota available.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: false,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Jomtien Beach Road',
      addressLine2: 'Na Jomtien',
      cityId: pattaya.id,
      countryId: thailand.id,
      latitude: 12.8822,
      longitude: 100.8989,
      bedrooms: 1,
      bathrooms: 1,
      areaSize: 42,
      areaUnit: 'sqm',
      yearBuilt: 2015,
      price: 2800000,
      priceCurrencyId: thb?.id,
      publishedAt: new Date(),
    },

    // ========================================
    // THAILAND - PHUKET - LOCATION (RENT)
    // ========================================
    {
      slug: 'villa-cherngtalay-phuket-rent',
      title: 'Luxury Pool Villa Cherngtalay',
      subtitle: '4BR Modern Villa',
      description: 'Modern 4-bedroom pool villa in peaceful Cherngtalay area. 10 minutes to Bang Tao Beach and Boat Avenue. Fully furnished, private pool, tropical garden, perfect for families.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Cherngtalay',
      addressLine2: 'Thalang, Phuket',
      cityId: phuket.id,
      countryId: thailand.id,
      latitude: 8.0253,
      longitude: 98.2978,
      bedrooms: 4,
      bathrooms: 4,
      parkingSpaces: 2,
      areaSize: 280,
      areaUnit: 'sqm',
      landArea: 400,
      landAreaUnit: 'sqm',
      yearBuilt: 2021,
      price: 150000,
      priceCurrencyId: thb?.id,
      pricePostfix: '/month',
      publishedAt: new Date(),
    },

    // ========================================
    // THAILAND - PHUKET - VENTE (SALE)
    // ========================================
    {
      slug: 'seaview-villa-kamala-phuket-sale',
      title: 'Sea View Villa Kamala Beach',
      subtitle: '5BR Luxury Sea View Villa',
      description: 'Breathtaking 5-bedroom sea view villa in Kamala. Infinity pool overlooking Andaman Sea, modern tropical design, 4 parking spaces. Chanote title, foreign freehold possible.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Kamala Heights',
      addressLine2: 'Kamala, Kathu',
      cityId: phuket.id,
      countryId: thailand.id,
      latitude: 7.9614,
      longitude: 98.2817,
      bedrooms: 5,
      bathrooms: 6,
      parkingSpaces: 4,
      areaSize: 450,
      areaUnit: 'sqm',
      landArea: 600,
      landAreaUnit: 'sqm',
      yearBuilt: 2020,
      price: 42000000,
      priceCurrencyId: thb?.id,
      publishedAt: new Date(),
    },
    {
      slug: 'condo-rawai-phuket-sale',
      title: 'Beachfront Condo Rawai',
      subtitle: '2BR Investment Condo',
      description: '2-bedroom beachfront condo in Rawai. Sea view, community pool, gym. Great rental yield area. Foreign quota.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: false,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Rawai Beach',
      addressLine2: 'Rawai, Mueang Phuket',
      cityId: phuket.id,
      countryId: thailand.id,
      latitude: 7.7756,
      longitude: 98.3264,
      bedrooms: 2,
      bathrooms: 2,
      areaSize: 68,
      areaUnit: 'sqm',
      yearBuilt: 2019,
      price: 6500000,
      priceCurrencyId: thb?.id,
      publishedAt: new Date(),
    },

    // ========================================
    // THAILAND - OFF-PLAN (INVESTMENT)
    // ========================================
    {
      slug: 'offplan-condo-ekkamai-bangkok',
      title: 'Off-Plan Condo Ekkamai BTS',
      subtitle: 'Pre-Launch 1BR Investment',
      description: 'Brand new development launching Q1 2026. Prime Ekkamai location next to BTS. 1 bedroom starting from 4.5M THB. 20% down payment, flexible payment plan. Expected 8% rental yield. Completion Q4 2027.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.INVESTMENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Sukhumvit 63 (Ekkamai)',
      addressLine2: 'Phra Khanong, Watthana',
      cityId: bangkok.id,
      countryId: thailand.id,
      latitude: 13.7250,
      longitude: 100.5850,
      bedrooms: 1,
      bathrooms: 1,
      parkingSpaces: 1,
      areaSize: 35,
      areaUnit: 'sqm',
      price: 4500000,
      priceCurrencyId: thb?.id,
      rentalDetails: {
        completionDate: 'Q4 2027',
        downPayment: '20%',
        expectedYield: '8%',
        paymentPlan: 'Flexible',
      },
      publishedAt: new Date(),
    },
    {
      slug: 'offplan-pool-villa-pattaya',
      title: 'Off-Plan Pool Villa Bang Saray',
      subtitle: 'Pre-Sale 3BR Villas',
      description: 'New villa project in peaceful Bang Saray area. 3-bedroom pool villas starting from 8.9M THB. Modern design, private pool, 2 parking. 30% down payment. Completion mid-2026. Foreign freehold available.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.INVESTMENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Bang Saray',
      addressLine2: 'Sattahip, Chonburi',
      cityId: pattaya.id,
      countryId: thailand.id,
      latitude: 12.7456,
      longitude: 100.9234,
      bedrooms: 3,
      bathrooms: 3,
      parkingSpaces: 2,
      areaSize: 220,
      areaUnit: 'sqm',
      landArea: 180,
      landAreaUnit: 'sqw',
      price: 8900000,
      priceCurrencyId: thb?.id,
      rentalDetails: {
        completionDate: 'Mid-2026',
        downPayment: '30%',
        foreignFreehold: 'Available',
      },
      publishedAt: new Date(),
    },

    // ========================================
    // DUBAI - LOCATION (RENT)
    // ========================================
    {
      slug: 'penthouse-marina-dubai-rent',
      title: 'Luxury Penthouse Dubai Marina',
      subtitle: '3BR Duplex Penthouse',
      description: 'Exclusive 3-bedroom duplex penthouse in Dubai Marina with panoramic marina and sea views. Private rooftop terrace, maid room, 3 parking spaces. Premium finishes, smart home system.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Dubai Marina Walk',
      addressLine2: 'Dubai Marina',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.0777,
      longitude: 55.1410,
      bedrooms: 3,
      bathrooms: 4,
      parkingSpaces: 3,
      areaSize: 280,
      areaUnit: 'sqm',
      yearBuilt: 2019,
      price: 350000,
      priceCurrencyId: aed?.id,
      pricePostfix: '/year',
      rentalDetails: {
        deposit: 35000,
        chiller: 'Extra',
        parking: '3 spaces',
        maid: 'Maid room included',
      },
      publishedAt: new Date(),
    },
    {
      slug: 'apartment-jbr-dubai-rent',
      title: 'Beachfront Apartment JBR',
      subtitle: '2BR with Beach Access',
      description: '2-bedroom apartment in Jumeirah Beach Residence with direct beach access. Fully furnished, stunning sea views, gym, pool. Walk to The Beach mall and restaurants.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'The Walk, JBR',
      addressLine2: 'Dubai Marina',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.0754,
      longitude: 55.1371,
      bedrooms: 2,
      bathrooms: 2,
      parkingSpaces: 2,
      areaSize: 140,
      areaUnit: 'sqm',
      yearBuilt: 2020,
      price: 180000,
      priceCurrencyId: aed?.id,
      pricePostfix: '/year',
      publishedAt: new Date(),
    },
    {
      slug: 'villa-arabian-ranches-dubai-rent',
      title: 'Family Villa Arabian Ranches',
      subtitle: '4BR Villa with Garden',
      description: '4-bedroom villa in prestigious Arabian Ranches. Private garden, maid room, 2 parking, golf course views. Gated community with parks, pools, and schools.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.RENT,
      isFeatured: false,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Arabian Ranches',
      addressLine2: 'Dubailand',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.0536,
      longitude: 55.2645,
      bedrooms: 4,
      bathrooms: 4,
      parkingSpaces: 2,
      areaSize: 320,
      areaUnit: 'sqm',
      landArea: 500,
      landAreaUnit: 'sqm',
      yearBuilt: 2018,
      price: 220000,
      priceCurrencyId: aed?.id,
      pricePostfix: '/year',
      publishedAt: new Date(),
    },

    // ========================================
    // DUBAI - VENTE (SALE)
    // ========================================
    {
      slug: 'penthouse-downtown-burj-dubai-sale',
      title: 'Exclusive Penthouse Downtown',
      subtitle: '4BR Burj Khalifa View',
      description: 'Ultra-luxury 4-bedroom penthouse in Downtown Dubai with unobstructed Burj Khalifa views. Premium Italian finishes, private lift, smart home, 4 parking spaces. Rare opportunity.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Boulevard Heights',
      addressLine2: 'Downtown Dubai',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.1952,
      longitude: 55.2755,
      bedrooms: 4,
      bathrooms: 5,
      parkingSpaces: 4,
      areaSize: 420,
      areaUnit: 'sqm',
      yearBuilt: 2020,
      price: 12500000,
      priceCurrencyId: aed?.id,
      publishedAt: new Date(),
    },
    {
      slug: 'villa-palm-frond-dubai-sale',
      title: 'Beachfront Villa Palm Jumeirah',
      subtitle: '6BR Signature Villa',
      description: 'Magnificent 6-bedroom villa on Palm Jumeirah Frond with private beach access. Infinity pool, landscaped garden, cinema room, gym. Vacant on transfer, ready to move.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Frond G',
      addressLine2: 'Palm Jumeirah',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.1142,
      longitude: 55.1456,
      bedrooms: 6,
      bathrooms: 7,
      parkingSpaces: 5,
      areaSize: 850,
      areaUnit: 'sqm',
      landArea: 1200,
      landAreaUnit: 'sqm',
      yearBuilt: 2017,
      price: 25000000,
      priceCurrencyId: aed?.id,
      publishedAt: new Date(),
    },
    {
      slug: 'apartment-dubai-hills-sale',
      title: 'Modern Apartment Dubai Hills',
      subtitle: '2BR Golf Course View',
      description: '2-bedroom apartment in Dubai Hills Estate with golf course views. Brand new, modern design, community pool and gym. Great for end-users or investors.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: false,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Dubai Hills Estate',
      addressLine2: 'Mohammed Bin Rashid City',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.1003,
      longitude: 55.2456,
      bedrooms: 2,
      bathrooms: 2,
      parkingSpaces: 2,
      areaSize: 110,
      areaUnit: 'sqm',
      yearBuilt: 2022,
      price: 2100000,
      priceCurrencyId: aed?.id,
      publishedAt: new Date(),
    },
    {
      slug: 'townhouse-damac-hills-dubai-sale',
      title: 'Townhouse DAMAC Hills',
      subtitle: '3BR Corner Unit',
      description: '3-bedroom corner townhouse in DAMAC Hills community. Private garden, 2 parking, maid room. Community amenities include Trump golf course, pools, parks.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.SALE,
      isFeatured: false,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'DAMAC Hills',
      addressLine2: 'Dubailand',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.0425,
      longitude: 55.2156,
      bedrooms: 3,
      bathrooms: 3,
      parkingSpaces: 2,
      areaSize: 220,
      areaUnit: 'sqm',
      landArea: 180,
      landAreaUnit: 'sqm',
      yearBuilt: 2021,
      price: 2650000,
      priceCurrencyId: aed?.id,
      publishedAt: new Date(),
    },

    // ========================================
    // DUBAI - OFF-PLAN (INVESTMENT)
    // ========================================
    {
      slug: 'offplan-tower-creek-harbour-dubai',
      title: 'Off-Plan Tower Creek Harbour',
      subtitle: 'Pre-Launch 1BR Creek Views',
      description: 'Brand new development by Emaar in Dubai Creek Harbour. 1 bedroom with Creek and Burj Khalifa views. Starting from 1.2M AED. 20% down payment, 3-year payment plan. Q2 2028 completion. Expected ROI 9%.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.INVESTMENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Dubai Creek Harbour',
      addressLine2: 'Ras Al Khor',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.1789,
      longitude: 55.3289,
      bedrooms: 1,
      bathrooms: 1,
      parkingSpaces: 1,
      areaSize: 65,
      areaUnit: 'sqm',
      price: 1200000,
      priceCurrencyId: aed?.id,
      rentalDetails: {
        developer: 'Emaar',
        completionDate: 'Q2 2028',
        downPayment: '20%',
        paymentPlan: '80/20 - 3 years',
        expectedROI: '9%',
      },
      publishedAt: new Date(),
    },
    {
      slug: 'offplan-villas-tilal-al-ghaf-dubai',
      title: 'Off-Plan Villas Tilal Al Ghaf',
      subtitle: 'Pre-Sale 4BR Luxury Villas',
      description: 'New villa community by Majid Al Futtaim. 4-bedroom villas starting from 4.5M AED. Lagoon community with beach, parks, schools. 25% down payment, 3-year payment plan. Q4 2027 handover.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.INVESTMENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Tilal Al Ghaf',
      addressLine2: 'Hessa Street',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.0678,
      longitude: 55.1845,
      bedrooms: 4,
      bathrooms: 4,
      parkingSpaces: 2,
      areaSize: 320,
      areaUnit: 'sqm',
      landArea: 450,
      landAreaUnit: 'sqm',
      price: 4500000,
      priceCurrencyId: aed?.id,
      rentalDetails: {
        developer: 'Majid Al Futtaim',
        completionDate: 'Q4 2027',
        downPayment: '25%',
        paymentPlan: '75/25 - 3 years',
        lagoon: 'Access included',
      },
      publishedAt: new Date(),
    },
    {
      slug: 'offplan-penthouse-business-bay-dubai',
      title: 'Off-Plan Penthouse Business Bay',
      subtitle: 'Sky Collection 3BR',
      description: 'Ultra-luxury 3-bedroom penthouse in new Business Bay tower. Burj Khalifa views, private pool on terrace. Starting 8.5M AED. 30% down payment. Q1 2029 completion. Furniture package available.',
      status: PropertyStatus.PUBLISHED,
      type: PropertyType.INVESTMENT,
      isFeatured: true,
      visibility: PropertyVisibility.PUBLIC,
      addressLine1: 'Business Bay',
      addressLine2: 'Business Bay Towers',
      cityId: dubai.id,
      countryId: uae.id,
      latitude: 25.1856,
      longitude: 55.2689,
      bedrooms: 3,
      bathrooms: 4,
      parkingSpaces: 3,
      areaSize: 280,
      areaUnit: 'sqm',
      price: 8500000,
      priceCurrencyId: aed?.id,
      rentalDetails: {
        completionDate: 'Q1 2029',
        downPayment: '30%',
        paymentPlan: '70/30 - 4 years',
        privateTerrace: 'With pool',
        furniture: 'Package available',
      },
      publishedAt: new Date(),
    },
  ];

  let created = 0;
  let updated = 0;

  for (const property of properties) {
    try {
      const result = await prisma.property.upsert({
        where: { slug: property.slug },
        update: {
          ...property,
          updatedAt: new Date(),
        },
        create: property,
      });
      
      if (result.createdAt.getTime() === result.updatedAt.getTime()) {
        created++;
        console.log(`✅ Created: ${property.title} (${property.type})`);
      } else {
        updated++;
        console.log(`🔄 Updated: ${property.title} (${property.type})`);
      }
    } catch (error) {
      console.error(`❌ Error with ${property.title}:`, error);
    }
  }

  console.log(`\n🎉 Complete properties seeding finished!`);
  console.log(`   ✨ Created: ${created} properties`);
  console.log(`   🔄 Updated: ${updated} properties`);
  console.log(`   📊 Total: ${created + updated} properties`);
  
  console.log(`\n📍 Breakdown by City:`);
  console.log(`   - Bangkok: 5 properties (2 RENT, 2 SALE, 1 OFF-PLAN)`);
  console.log(`   - Pattaya: 4 properties (1 RENT, 2 SALE, 1 OFF-PLAN)`);
  console.log(`   - Phuket: 3 properties (1 RENT, 2 SALE)`);
  console.log(`   - Dubai: 11 properties (3 RENT, 5 SALE, 3 OFF-PLAN)`);
  
  console.log(`\n🏷️ Breakdown by Type:`);
  console.log(`   - RENT (Location): 7 properties`);
  console.log(`   - SALE (Vente): 11 properties`);
  console.log(`   - INVESTMENT (Off-Plan): 5 properties`);
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
